//! W3-FIX-SEC-001 — X-Org-Id auth enforcement tests for `prism-dtu-claroty`.
//!
//! Exercises BC-3.5.001, BC-3.5.002, and BC-3.2.001 per the story acceptance criteria.
//!
//! # Red Gate (Phase 2)
//!
//! Test bodies replaced with real assertion-driven logic. Tests for AC-002, AC-003,
//! EC-001, EC-003, and AC-005 assert HTTP 401 on mismatch/missing/malformed org
//! headers. These tests currently FAIL with "expected 401, got 200" because
//! `validate_org_id` is `todo!()` and not yet wired into route handlers.
//!
//! AC-001 tests the positive path (same-org → 200). With the current implementation
//! that uses `extract_org_id` with a sentinel fallback, these may pass early — that
//! is acceptable; the Red Gate failures are in AC-002, AC-003, and the EC tests.
//!
//! # Acceptance Criteria covered
//!
//! | AC | Description |
//! |----|-------------|
//! | AC-001 | Same-org request succeeds (BC-3.2.001 postcondition 1) |
//! | AC-002 | Cross-org spoofing returns HTTP 401 (BC-3.5.002 precondition 3) |
//! | AC-003 | Missing header returns HTTP 401 (BC-3.5.001 postcondition 1) |
//! | AC-004 | All four DTU clones covered (BC-3.2.001 invariant 1) |
//! | AC-005 | Regression: `test_cross_org_header_rejected` (BC-3.5.002 precondition 3) |
//! | AC-006 | Positive paths in existing tests still pass (BC-3.5.001 postcondition 1) |
//!
//! # Edge cases covered
//!
//! | EC | Description |
//! |----|-------------|
//! | EC-001 | Non-UUID value in X-Org-Id header → HTTP 401 |
//! | EC-003 | Sentinel UUID sent as header → HTTP 401 |
//! | EC-004 | `reset_for/{org_id}` path param validated against instance_org_id → 403 |

#![allow(clippy::expect_used, clippy::unwrap_used, non_snake_case)]
#![cfg(feature = "dtu")]

use std::sync::Arc;

use prism_core::OrgId;
use prism_dtu_claroty::{ClarotyClone, ClarotyState};
use prism_dtu_common::BehavioralClone;

// ---------------------------------------------------------------------------
// Sentinel UUID — NEVER a valid instance_org_id
// ---------------------------------------------------------------------------

const SENTINEL_UUID: &str = "00000000-0000-7000-8000-000000000000";

// ---------------------------------------------------------------------------
// Test helper: start a clone whose instance_org_id is set to `org_id`.
//
// Claroty exposes `pub state: Arc<ClarotyState>`, so we can swap in a state
// with the desired instance_org_id before starting.
// ---------------------------------------------------------------------------

async fn start_clone_with_org(org_id: OrgId) -> (ClarotyClone, String) {
    let mut clone = ClarotyClone::new();
    // Retrieve the admin token generated by new() before we replace the state.
    let token = clone.admin_token().to_string();
    // Replace the state with one that has the desired instance_org_id.
    clone.state = Arc::new(ClarotyState::with_admin_token_and_org(token, org_id));
    clone.start().await.expect("ClarotyClone::start failed");
    let base_url = clone.base_url();
    (clone, base_url)
}

/// Build a reqwest Client with a short timeout for testing.
fn http_client() -> reqwest::Client {
    reqwest::Client::builder()
        .timeout(std::time::Duration::from_secs(5))
        .build()
        .expect("reqwest::Client build")
}

// ---------------------------------------------------------------------------
// Deterministic test OrgIds
// ---------------------------------------------------------------------------

fn org_a() -> OrgId {
    OrgId::from_uuid(
        uuid::Uuid::parse_str("00000000-0000-7000-8000-0000000000AA").expect("valid uuid"),
    )
}

fn org_b() -> OrgId {
    OrgId::from_uuid(
        uuid::Uuid::parse_str("00000000-0000-7000-8000-0000000000BB").expect("valid uuid"),
    )
}

// ===========================================================================
// AC-001 — Same-org request succeeds (BC-3.2.001 postcondition 1)
// ===========================================================================

/// AC-001 / BC-3.2.001 postcondition 1:
/// A request supplying `X-Org-Id: <instance_org_id>` receives HTTP 200.
/// Handler derives OrgId from clone state AND verifies the header matches.
///
/// Traces to: BC-3.2.001 postcondition 1, W3-FIX-SEC-001 AC-001.
#[tokio::test]
async fn test_AC_001_x_org_id_validated_against_bearer_token() {
    let instance_org = org_a();
    let (_clone, base_url) = start_clone_with_org(instance_org).await;
    let client = http_client();

    let resp = client
        .post(format!("{base_url}/api/v1/devices"))
        .header("Authorization", "Bearer test-token")
        .header("X-Org-Id", instance_org.as_uuid().to_string())
        .send()
        .await
        .expect("AC-001: request must not error");

    assert_eq!(
        resp.status().as_u16(),
        200,
        "AC-001: POST /api/v1/devices with matching X-Org-Id must return HTTP 200; \
         got {} — validate_org_id is not yet wired into route handlers",
        resp.status().as_u16()
    );
}

// ===========================================================================
// AC-002 — Cross-org spoofing returns 401 (BC-3.5.002 precondition 3)
// ===========================================================================

/// AC-002 / BC-3.5.002 precondition 3:
/// A request supplying a different org's UUID in `X-Org-Id` receives HTTP 401
/// with JSON body `{"error": "org_id mismatch: request does not match this clone instance"}`.
/// Clone internal state is NOT accessed or modified.
///
/// Traces to: BC-3.5.002 precondition 3, W3-FIX-SEC-001 AC-002.
#[tokio::test]
async fn test_AC_002_cross_org_credential_returns_401() {
    // Clone is bound to org_a; caller supplies org_b UUID.
    let (_clone, base_url) = start_clone_with_org(org_a()).await;
    let client = http_client();

    let resp = client
        .post(format!("{base_url}/api/v1/devices"))
        .header("Authorization", "Bearer test-token")
        .header("X-Org-Id", org_b().as_uuid().to_string())
        .send()
        .await
        .expect("AC-002: request must not error");

    assert_eq!(
        resp.status().as_u16(),
        401,
        "AC-002: POST /api/v1/devices with mismatched X-Org-Id must return HTTP 401; \
         got {} — validate_org_id is not yet wired into list_devices handler",
        resp.status().as_u16()
    );
}

/// AC-002 variant — JSON error body has expected shape.
///
/// The 401 response body MUST be `{"error": "org_id mismatch: ..."}` (not plain text).
/// Traces to: W3-FIX-SEC-001 AC-002, Architecture Compliance Rule §3.
#[tokio::test]
async fn test_AC_002_cross_org_401_body_is_json_error_object() {
    let (_clone, base_url) = start_clone_with_org(org_a()).await;
    let client = http_client();

    let resp = client
        .post(format!("{base_url}/api/v1/devices"))
        .header("Authorization", "Bearer test-token")
        .header("X-Org-Id", org_b().as_uuid().to_string())
        .send()
        .await
        .expect("AC-002 body: request must not error");

    // First gate: status must be 401.
    assert_eq!(
        resp.status().as_u16(),
        401,
        "AC-002 body: expected HTTP 401 for cross-org header; got {}",
        resp.status().as_u16()
    );

    let body: serde_json::Value = resp
        .json()
        .await
        .expect("AC-002 body: 401 response must be valid JSON");

    let error_msg = body["error"].as_str().unwrap_or("");
    assert!(
        error_msg.contains("org_id mismatch"),
        "AC-002 body: error field must contain 'org_id mismatch'; got: {error_msg:?}"
    );
}

// ===========================================================================
// AC-003 — Missing header returns 401 (BC-3.5.001 postcondition 1)
// ===========================================================================

/// AC-003 / BC-3.5.001 postcondition 1:
/// A request that omits the `X-Org-Id` header entirely receives HTTP 401.
/// The sentinel UUID fallback (`00000000-0000-7000-8000-000000000000`) must NOT
/// be accepted as a valid org.
///
/// Traces to: BC-3.5.001 postcondition 1, W3-FIX-SEC-001 AC-003.
#[tokio::test]
async fn test_AC_003_missing_x_org_id_header_returns_401() {
    let (_clone, base_url) = start_clone_with_org(org_a()).await;
    let client = http_client();

    // No X-Org-Id header at all.
    let resp = client
        .post(format!("{base_url}/api/v1/devices"))
        .header("Authorization", "Bearer test-token")
        .send()
        .await
        .expect("AC-003: request must not error");

    assert_eq!(
        resp.status().as_u16(),
        401,
        "AC-003: POST /api/v1/devices without X-Org-Id header must return HTTP 401; \
         got {} — sentinel fallback must be rejected by validate_org_id",
        resp.status().as_u16()
    );
}

// ===========================================================================
// AC-005 — Regression: test_cross_org_header_rejected (BC-3.5.002 precondition 3)
// ===========================================================================

/// AC-005 / BC-3.5.002 precondition 3:
/// Integration test demonstrating credential-mismatch returns HTTP 401.
/// Verifies it is NOT HTTP 200 and NOT a silent empty response.
///
/// This is the canonical regression guard for HS-003-02 invariant.
/// Traces to: BC-3.5.002 precondition 3, W3-FIX-SEC-001 AC-005.
#[tokio::test]
async fn test_cross_org_header_rejected() {
    let (_clone, base_url) = start_clone_with_org(org_a()).await;
    let client = http_client();

    let resp = client
        .post(format!("{base_url}/api/v1/devices"))
        .header("Authorization", "Bearer test-token")
        .header("X-Org-Id", org_b().as_uuid().to_string())
        .send()
        .await
        .expect("AC-005: request must not error");

    let status = resp.status().as_u16();

    // MUST be 401 — not 200 and not a silent empty response.
    assert_eq!(
        status, 401,
        "AC-005: cross-org credential mismatch must return HTTP 401, not {status}"
    );
    // MUST have a non-empty body (not silent empty).
    let body_bytes = resp
        .bytes()
        .await
        .expect("AC-005: response body must be readable");
    assert!(
        !body_bytes.is_empty(),
        "AC-005: 401 response body must not be empty (silent rejection is not allowed)"
    );
}

// ===========================================================================
// EC-001 — Non-UUID value in X-Org-Id → 401
// ===========================================================================

/// EC-001:
/// When `X-Org-Id` is present but not a valid UUID string, the handler must
/// return HTTP 401 (not 400, not 500) with `{"error": "org_id mismatch: ..."}`.
/// Clone state is NOT accessed.
///
/// Traces to: W3-FIX-SEC-001 EC-001.
#[tokio::test]
async fn test_EC_001_non_uuid_x_org_id_returns_401() {
    let (_clone, base_url) = start_clone_with_org(org_a()).await;
    let client = http_client();

    let resp = client
        .post(format!("{base_url}/api/v1/devices"))
        .header("Authorization", "Bearer test-token")
        .header("X-Org-Id", "not-a-uuid-at-all")
        .send()
        .await
        .expect("EC-001: request must not error");

    assert_eq!(
        resp.status().as_u16(),
        401,
        "EC-001: non-UUID X-Org-Id header must return HTTP 401; \
         got {} — validate_org_id must treat unparseable headers as mismatch",
        resp.status().as_u16()
    );
}

// ===========================================================================
// EC-003 — Sentinel UUID sent as header → 401
// ===========================================================================

/// EC-003:
/// Sending the sentinel UUID `00000000-0000-7000-8000-000000000000` as the
/// `X-Org-Id` header must return HTTP 401. The sentinel is NOT the clone's
/// `instance_org_id` (which is a deterministic non-sentinel UUID).
///
/// Traces to: W3-FIX-SEC-001 EC-003.
#[tokio::test]
async fn test_EC_003_sentinel_uuid_as_x_org_id_returns_401() {
    let (_clone, base_url) = start_clone_with_org(org_a()).await;
    let client = http_client();

    let resp = client
        .post(format!("{base_url}/api/v1/devices"))
        .header("Authorization", "Bearer test-token")
        .header("X-Org-Id", SENTINEL_UUID)
        .send()
        .await
        .expect("EC-003: request must not error");

    assert_eq!(
        resp.status().as_u16(),
        401,
        "EC-003: sentinel UUID in X-Org-Id must return HTTP 401; \
         got {} — sentinel must not be accepted as a valid org identity",
        resp.status().as_u16()
    );
}

// ===========================================================================
// EC-004 — reset_for/{org_id} path param validated → 403 on mismatch
// ===========================================================================

/// EC-004:
/// `POST /dtu/reset_for/{org_id}` where `org_id` does NOT match `instance_org_id`
/// must return HTTP 403 (distinct from the header-check 401).
///
/// Traces to: W3-FIX-SEC-001 EC-004.
#[tokio::test]
async fn test_EC_004_reset_for_wrong_org_returns_403() {
    let (clone, base_url) = start_clone_with_org(org_a()).await;
    let client = http_client();
    let admin_token = clone.admin_token().to_string();

    // Send org_b UUID in the path — clone is bound to org_a.
    let resp = client
        .post(format!("{base_url}/dtu/reset_for/{}", org_b().as_uuid()))
        .header("X-Admin-Token", &admin_token)
        .send()
        .await
        .expect("EC-004: request must not error");

    assert_eq!(
        resp.status().as_u16(),
        403,
        "EC-004: reset_for path param mismatch must return HTTP 403; \
         got {} — path-param org validation must be implemented in dtu_reset_for handler",
        resp.status().as_u16()
    );
}
