//! TrustLevel — trust-level metadata for MCP responses (BC-2.09.005).
//!
//! Binary enum: `UntrustedExternal` for sensor data, `Internal` for Prism-generated data.
//! `UntrustedExternal` is the more restrictive level and wins in mixed scenarios.

use serde::{Deserialize, Serialize};

/// Trust level for a Prism MCP tool response.
///
/// BC-2.09.005: every response carries exactly one of these values.
/// When a response mixes internal and sensor-derived content,
/// `UntrustedExternal` (more restrictive) applies.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum TrustLevel {
    /// Data originates from external sensor APIs monitoring adversarial environments.
    /// All field values may contain attacker-controlled content.
    UntrustedExternal,
    /// Data is generated by Prism itself (health checks, capability listings, errors).
    Internal,
}

impl TrustLevel {
    /// Returns the wire-format string used in `_meta.trust_level`.
    ///
    /// BC-2.09.005: exactly `"untrusted_external"` or `"internal"`.
    pub fn as_str(&self) -> &'static str {
        match self {
            TrustLevel::UntrustedExternal => "untrusted_external",
            TrustLevel::Internal => "internal",
        }
    }

    /// Returns the more restrictive of two trust levels.
    ///
    /// BC-2.09.005: when mixing internal and sensor data, `UntrustedExternal` wins.
    pub fn most_restrictive(a: TrustLevel, b: TrustLevel) -> TrustLevel {
        match (a, b) {
            (TrustLevel::UntrustedExternal, _) | (_, TrustLevel::UntrustedExternal) => {
                TrustLevel::UntrustedExternal
            }
            _ => TrustLevel::Internal,
        }
    }
}
