//! Red Gate test 8: BC-2.06.019 PC-4 / TV-019-011
//!
//! test_BC_2_06_019_crowdstrike_containment_visible_at_stage4_only
//!
//! Traces to: BC-2.06.019 postcondition 4 / TV-019-011
//! Story: S-DEMO-DTU-LIVE-SCENARIO-001-B
//!
//! FAIL mode (Red Gate): `new_with_scenario` stub sets `timeline = None` in state.
//! Without timeline, the route handler cannot compute the current stage index and
//! apply the stage 4 mask filter. Consequently:
//! - The primary device's `containment_status = "contained"` record IS in
//!   `generated_devices` (generated by CompromisedEndpoint archetype).
//! - Without stage-mask filtering, it appears at ALL time points — including
//!   stage 2 (T+200s) where the `device_cves` mask is false and ONLY stages
//!   with `visible_entity_mask.primary_device=true` should show the device.
//!
//! The test directly asserts `state.timeline.is_some()` which FAILS because the
//! stub leaves it as `None`. This is the primary Red Gate failure.
//!
//! Additionally, once timeline is attached, the `current_stage_index` at T+200s
//! must return 2 (LateralMovement), and the test verifies that
//! `stage[2].visible_entity_mask.device_cves = false`, so at stage 2 the primary
//! device with `containment_status = "contained"` is NOT visible via stage mask.
//!
//! At T+700s (stage 4 / Containment): `device_cves=true` and all fields true,
//! so the primary device IS visible.

#![cfg(feature = "fixture-gen")]
#![allow(clippy::unwrap_used, clippy::expect_used)]

use std::sync::Arc;

use prism_dtu_common::{
    build_default_incident_timeline, build_scenario_entity_catalog, current_stage_index, Archetype,
    OrgId,
};
use prism_dtu_crowdstrike::CrowdstrikeClone;

/// Org ID with well-known first 4 bytes [0xde, 0xad, 0xbe, 0xef] → org_slug = "deadbeef".
fn deadbeef_org() -> OrgId {
    OrgId([
        0xde, 0xad, 0xbe, 0xef, 0x00, 0x00, 0x70, 0x00, 0x80, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00,
    ])
}

/// RED GATE TEST 8 — test_BC_2_06_019_crowdstrike_containment_visible_at_stage4_only
///
/// BC-2.06.019 PC-4 / TV-019-011
///
/// Verifies that:
/// 1. At T+200s (stage 2 / LateralMovement): `containment_status` device is NOT visible
///    (stage 2 mask: `device_cves=false` means that CVE-associated info is masked; the
///    primary device itself IS visible, but `containment_status` field's visibility is
///    governed by the stage-4 containment mask).
/// 2. At T+700s (stage 4 / Containment): the primary device with `containment_status="contained"`
///    IS visible (all fields true in stage 4 mask).
///
/// The story spec (AC-008) states:
/// > "The pre-built FixtureSet record already carries containment_status = 'contained'
/// >  for the CompromisedEndpoint primary device; the Containment stage mask makes it visible."
///
/// The canonical failing assertion is `state.timeline.is_some()`.
/// Once that fails, the secondary failing assertion is `stage2_idx == 2` (since
/// current_stage_index stub always returns 0).
#[test]
fn test_BC_2_06_019_crowdstrike_containment_visible_at_stage4_only() {
    let org = deadbeef_org();
    let seed: u64 = 100;

    let catalog = build_scenario_entity_catalog(seed, &org);
    let primary_device_id = catalog.primary_device_id_cs.clone();

    let start_secs: i64 = 1_000_000;
    let timeline = build_default_incident_timeline(catalog, start_secs, &[]);
    let timeline_arc = Arc::new(timeline);

    // Build a CrowdstrikeClone via new_with_scenario (5-arg stub).
    let clone = CrowdstrikeClone::new_with_scenario(
        seed,
        Archetype::CompromisedEndpoint,
        org,
        Arc::clone(&timeline_arc),
        chrono::DateTime::from_timestamp(start_secs, 0)
            .expect("valid timestamp")
            .with_timezone(&chrono::Utc),
    );

    // The clone must have generated_devices populated (CompromisedEndpoint produces devices).
    assert!(
        !clone.state.generated_devices.is_empty(),
        "CrowdstrikeClone::new_with_scenario with CompromisedEndpoint must produce \
         non-empty generated_devices; got empty. BC-2.06.019 PC-4"
    );

    // The clone must have timeline attached (proves scenario path was taken).
    // FAIL: stub leaves timeline = None.
    assert!(
        clone.state.timeline.is_some(),
        "CrowdstrikeClone::new_with_scenario must attach timeline to state.timeline (Some); \
         got None — BC-2.06.019 PC-4 / ADR-036 v2.3 §2.4 \
         [RED GATE: stub leaves timeline = None]"
    );

    // Find the primary device record with containment_status = "contained".
    let contained_records: Vec<&serde_json::Value> = clone
        .state
        .generated_devices
        .iter()
        .filter(|rec| {
            let device_id_match = rec
                .get("device_id")
                .and_then(|v| v.as_str())
                .map(|id| id == &primary_device_id)
                .unwrap_or(false);
            let is_contained = rec
                .get("containment_status")
                .and_then(|v| v.as_str())
                .map(|s| s == "contained")
                .unwrap_or(false);
            device_id_match && is_contained
        })
        .collect();

    // CompromisedEndpoint archetype must generate a primary device with containment_status="contained".
    // (This is the record that should only be visible at stage 4 via stage-mask filtering.)
    assert!(
        !contained_records.is_empty(),
        "CompromisedEndpoint archetype must generate a record for primary device \
         '{primary_device_id}' with containment_status='contained'; found 0 such records \
         among {} total generated_devices — BC-2.06.019 AC-008 / TV-019-011",
        clone.state.generated_devices.len()
    );

    // --- Stage 2 assertions (T+200s) ---
    // At T+200s (elapsed=200 >= 180), stage must be 2 (LateralMovement).
    // Stage 2 mask: device_cves=false (device CVE info is masked at this stage).
    let now_stage2 = start_secs + 200;
    let stage2_idx = current_stage_index(&timeline_arc, now_stage2);

    // FAIL: current_stage_index stub always returns 0, not 2.
    assert_eq!(
        stage2_idx, 2,
        "TV-019-011: at T+200s, stage index must be 2 (LateralMovement; elapsed 200 >= 180s); \
         got {stage2_idx} — BC-2.06.019 PC-3 / TV-019-011 \
         [RED GATE: current_stage_index stub always returns 0]"
    );

    // Stage 2 mask must have device_cves=false (containment stage gate for the device).
    // This assertion only runs if the above stage-index assertion passes (implementer phase).
    let stage2_mask = &timeline_arc.stages[stage2_idx].visible_entity_mask;
    assert!(
        !stage2_mask.device_cves,
        "Stage 2 (LateralMovement) mask must have device_cves=false; got true. \
         BC-2.06.019 PC-2 table / TV-019-011"
    );

    // --- Stage 4 assertions (T+700s) ---
    // At T+700s (elapsed=700 >= 600), stage must be 4 (Containment).
    // Stage 4 mask: all fields true (primary_device, lateral_devices, ioc_ips, ioc_domains,
    // ioc_hashes, device_cves all true).
    let now_stage4 = start_secs + 700;
    let stage4_idx = current_stage_index(&timeline_arc, now_stage4);

    // FAIL: current_stage_index stub always returns 0, not 4.
    assert_eq!(
        stage4_idx, 4,
        "TV-019-011: at T+700s, stage index must be 4 (Containment; elapsed 700 >= 600s); \
         got {stage4_idx} — BC-2.06.019 PC-3 / TV-019-011 \
         [RED GATE: current_stage_index stub always returns 0]"
    );
}
