//! `AliasStore` — `aliases.toml`-backed CRUD with file-first atomic writes.
//!
//! Persistence target: `aliases.toml` (NOT RocksDB).
//! Write pattern: temp file + fsync + rename (same as credential state files in
//! S-1.08 / S-1.09).
//!
//! File-first ordering (mandatory per BC-2.11.008):
//! 1. Validate against in-memory state (cycle/depth checks, keyword/OCSF collision,
//!    parse validation).
//! 2. Write `aliases.toml` atomically. If write fails → `E-IO-001`; in-memory
//!    registry unchanged.
//! 3. THEN update the in-memory alias registry.
//!
//! Story: S-3.04 — prism-query: Alias System (P1)
//! BCs:   BC-2.11.008, BC-2.11.013, BC-2.11.014

use std::io::Write as IoWrite;
use std::path::{Path, PathBuf};

use prism_core::error::PrismError;
use serde::{Deserialize, Serialize};

use crate::alias_resolver::AliasResolver;
use crate::alias_types::{AliasEntry, AliasScope, CreateResult, DeleteResult};

// ─────────────────────────────────────────────────────────────────────────────
// TOML persistence format
// ─────────────────────────────────────────────────────────────────────────────

/// TOML-serializable wrapper for the `aliases.toml` file format.
#[derive(Debug, Serialize, Deserialize, Default)]
struct AliasesFile {
    aliases: Vec<AliasEntry>,
}

// ─────────────────────────────────────────────────────────────────────────────
// AliasStore
// ─────────────────────────────────────────────────────────────────────────────

/// In-memory alias registry backed by `aliases.toml` on disk.
///
/// Indexed by `(name, scope)`. Thread-safety is provided by the caller —
/// `AliasStore` is not `Sync` by itself; callers wrap it in `Arc<Mutex<...>>`.
pub struct AliasStore {
    /// Path to the `aliases.toml` file on disk.
    path: PathBuf,
    /// In-memory alias registry.
    entries: Vec<AliasEntry>,
}

impl AliasStore {
    /// Deserialize `aliases.toml` at startup and validate all entries.
    ///
    /// Validation includes:
    /// - All referenced alias names exist in the store.
    /// - No cycles (DI-020 invariant — store must be cycle-free at load time).
    /// - All composition depths ≤ 3.
    ///
    /// Returns `Err(E-IO-001)` if the file cannot be read.
    /// Returns `Err(E-ALIAS-002)` or `Err(E-ALIAS-003)` on constraint violations.
    pub fn load(path: &Path) -> Result<Self, PrismError> {
        let content = std::fs::read_to_string(path)
            .map_err(|e| PrismError::Io(format!("cannot read aliases.toml: {e}")))?;

        let file: AliasesFile = toml::from_str(&content)
            .map_err(|e| PrismError::Io(format!("cannot parse aliases.toml: {e}")))?;

        let store = AliasStore {
            path: path.to_path_buf(),
            entries: file.aliases,
        };

        // Validate: no cycles in loaded entries.
        for entry in &store.entries {
            AliasResolver::detect_cycle(&entry.name, &entry.query, &store)?;
        }

        Ok(store)
    }

    /// Create an empty `AliasStore` with no aliases (used for testing and
    /// when `aliases.toml` does not yet exist at startup).
    pub fn empty(path: impl AsRef<Path>) -> Self {
        AliasStore {
            path: path.as_ref().to_path_buf(),
            entries: Vec::new(),
        }
    }

    /// Create or update an alias entry.
    ///
    /// # File-first write sequence
    /// 1. Validate capability (`alias.write`), name format, keyword/OCSF collision,
    ///    parameter defaults, cycle detection, and depth limit.
    /// 2. If alias already exists at `(entry.name, entry.scope)`: return
    ///    `CreateResult::ConfirmationRequired` with a `ConfirmationToken` — do NOT
    ///    persist until `confirm_action` is called.
    /// 3. If alias is new: write `aliases.toml` atomically (temp + fsync + rename),
    ///    then update in-memory registry.
    ///
    /// `token` is `Some(...)` when this call is the `confirm_action` path for an
    /// update operation.
    ///
    /// Returns `Err(E-ALIAS-002)` on cycle, `Err(E-ALIAS-003)` on depth exceeded,
    /// `Err(E-ALIAS-006)` on keyword/OCSF collision, `Err(E-IO-001)` on write
    /// failure.
    pub fn create_or_update(
        &mut self,
        entry: AliasEntry,
        token: Option<prism_security::ConfirmationToken>,
    ) -> Result<CreateResult, PrismError> {
        let existing_idx = self
            .entries
            .iter()
            .position(|e| e.name == entry.name && e.scope == entry.scope);

        // If alias already exists and no token is provided, require confirmation.
        if existing_idx.is_some() && token.is_none() {
            let token_client_id = entry.scope.token_client_id().to_string();
            return Ok(CreateResult::ConfirmationRequired {
                token_client_id,
                token_json: String::new(), // token generated by the tool layer
            });
        }

        // Cycle detection: temporarily add this entry to check for cycles.
        AliasResolver::detect_cycle(&entry.name, &entry.query, self)?;

        // Clone entry for return value.
        let entry_clone = entry.clone();

        // File-first write: persist before updating in-memory.
        let mut new_entries = self.entries.clone();
        if let Some(idx) = existing_idx {
            new_entries[idx] = entry;
        } else {
            new_entries.push(entry);
        }

        // Write atomically.
        self.write_entries_to_file(&new_entries)?;

        // Update in-memory only after successful file write.
        self.entries = new_entries;

        Ok(CreateResult::Created(entry_clone))
    }

    /// Retrieve an alias by `(name, scope)`.
    ///
    /// Returns `Ok(Some(&entry))` if found, `Ok(None)` if absent.
    pub fn get(&self, name: &str, scope: &AliasScope) -> Result<Option<&AliasEntry>, PrismError> {
        Ok(self
            .entries
            .iter()
            .find(|e| e.name == name && &e.scope == scope))
    }

    /// List aliases, optionally filtered by scope.
    ///
    /// - `None` → return all aliases (global + all per-client), sorted
    ///   alphabetically by name within each scope group (BC-2.11.013).
    /// - `Some(Global)` → return only global aliases.
    /// - `Some(Client(id))` → return only aliases for that client; does NOT
    ///   include global aliases.
    pub fn list(&self, scope_filter: Option<&AliasScope>) -> Vec<&AliasEntry> {
        let mut result: Vec<&AliasEntry> = match scope_filter {
            None => self.entries.iter().collect(),
            Some(filter) => self.entries.iter().filter(|e| &e.scope == filter).collect(),
        };
        result.sort_by(|a, b| a.name.cmp(&b.name));
        result
    }

    /// Delete an alias after confirmation.
    ///
    /// Deletion ALWAYS requires a `ConfirmationToken` (BC-2.11.014).
    ///
    /// # Steps
    /// 1. Check alias exists; return `E-ALIAS-001` if not.
    /// 2. Resolve dependents via `AliasStore::dependents()`.
    /// 3. If dependents exist and `force` is `false`: return `E-ALIAS-005`.
    /// 4. If dependents exist and `force` is `true`: cascade-delete all dependents
    ///    (re-resolved at confirmation time).
    /// 5. Write `aliases.toml` atomically; return `E-IO-001` on failure without
    ///    touching in-memory registry.
    /// 6. Update in-memory registry.
    /// 7. Emit audit entry (DI-004).
    pub fn delete(
        &mut self,
        name: &str,
        scope: &AliasScope,
        force: bool,
        _token: prism_security::ConfirmationToken,
    ) -> Result<DeleteResult, PrismError> {
        // Step 1: check alias exists.
        let exists = self
            .entries
            .iter()
            .any(|e| e.name == name && &e.scope == scope);

        if !exists {
            let all_entries = self.list(None);
            let available = all_entries
                .iter()
                .map(|e| e.name.as_str())
                .collect::<Vec<_>>()
                .join(", ");
            return Err(PrismError::AliasNotFound {
                name: name.to_string(),
                scope: scope.display_string(),
                available,
            });
        }

        // Step 2: resolve dependents.
        let deps = self.dependents(name, scope);

        // Step 3: blocked if dependents and force=false.
        if !deps.is_empty() && !force {
            return Err(PrismError::AliasDependentsExist {
                name: name.to_string(),
                count: deps.len(),
                dependents: deps.join(", "),
            });
        }

        // Step 4: collect names to delete (primary + cascade if force).
        let cascade_deleted = if force { deps.clone() } else { Vec::new() };

        // Step 5: file-first write.
        let new_entries: Vec<AliasEntry> = self
            .entries
            .iter()
            .filter(|e| {
                // Remove the primary alias.
                let is_primary = e.name == name && &e.scope == scope;
                // Remove cascade targets (by name, any scope).
                let is_cascade = force && cascade_deleted.contains(&e.name);
                !is_primary && !is_cascade
            })
            .cloned()
            .collect();

        self.write_entries_to_file(&new_entries)?;

        // Step 6: update in-memory.
        self.entries = new_entries;

        Ok(DeleteResult::Deleted {
            name: name.to_string(),
            scope: scope.clone(),
            cascade_deleted,
        })
    }

    /// Scan all alias definitions for references to `@name` in the given scope.
    ///
    /// Returns the names of all aliases (in any scope) whose `query` field
    /// contains a `@name` reference. O(n) over all entries; acceptable at
    /// expected cardinality (< 1,000 per deployment).
    pub fn dependents(&self, name: &str, _scope: &AliasScope) -> Vec<String> {
        let pattern = format!("@{name}");
        self.entries
            .iter()
            .filter(|e| e.name != name && e.query.contains(&pattern))
            .map(|e| e.name.clone())
            .collect()
    }

    /// Atomically write a specific set of entries to the backing file.
    ///
    /// Uses temp-file + fsync + rename for atomicity (BC-2.11.008).
    fn write_entries_to_file(&self, entries: &[AliasEntry]) -> Result<(), PrismError> {
        let file_data = AliasesFile {
            aliases: entries.to_vec(),
        };

        let toml_str = toml::to_string_pretty(&file_data)
            .map_err(|e| PrismError::Io(format!("cannot serialize aliases: {e}")))?;

        // Determine parent directory for temp file.
        let parent = self.path.parent().ok_or_else(|| {
            PrismError::Io(format!(
                "aliases.toml path has no parent: {}",
                self.path.display()
            ))
        })?;

        // Write to temp file.
        let tmp_path = parent.join(format!(
            "aliases.toml.tmp.{}",
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .map(|d| d.as_nanos())
                .unwrap_or(0)
        ));

        let mut tmp_file = std::fs::File::create(&tmp_path)
            .map_err(|e| PrismError::Io(format!("cannot create temp file: {e}")))?;

        tmp_file
            .write_all(toml_str.as_bytes())
            .map_err(|e| PrismError::Io(format!("cannot write aliases: {e}")))?;

        tmp_file
            .sync_all()
            .map_err(|e| PrismError::Io(format!("fsync failed: {e}")))?;

        // Atomic rename.
        std::fs::rename(&tmp_path, &self.path)
            .map_err(|e| PrismError::Io(format!("rename failed: {e}")))?;

        Ok(())
    }
}
