//! Red Gate test for S-DEMO-003 AC-001 — BC-2.06.001 TOML config loading contract.
//!
//! # Contract under test
//!
//! BC-2.06.001 postcondition: "All `[clients.{id}]` sections are deserialized into
//! `ClientConfig` structs" — i.e., the TOML config file generated by `demo-setup.sh`
//! MUST be accepted by the `PrismConfig` deserializer at startup without error.
//!
//! AC-001 of S-DEMO-003 (traces to BC-2.06.001): after `scripts/demo-setup.sh` runs,
//! the generated `~/.config/prism-demo/prism.toml` must be schema-valid and
//! deserializable via `toml::from_str::<PrismConfig>()`.
//!
//! # Testable seam
//!
//! Rather than depending on `scripts/demo-setup.sh` (which does not exist during the
//! Red Gate phase), the test exercises `credential_cli::generate_demo_prism_toml()` —
//! a Rust helper function that returns the canonical demo `prism.toml` content.
//!
//! The test-writer's rationale for this seam choice:
//! 1. `demo-setup.sh` does not exist during the Red Gate phase. Running the script would
//!    produce a file-not-found error, not a meaningful assertion about the TOML contract.
//! 2. The Rust helper gives the implementer a clear, in-process unit that `demo-setup.sh`
//!    can mirror or invoke to generate `~/.config/prism-demo/prism.toml`.
//! 3. The test exercises the `PrismConfig` deserializer directly — exactly the code path
//!    that boot step 2 calls at runtime (BC-2.06.001 postcondition).
//!
//! # Red Gate requirement
//!
//! This test MUST FAIL before the implementer adds a real implementation to
//! `generate_demo_prism_toml()`. The current stub panics with `todo!()`.
//!
//! Story: S-DEMO-003 | BC: BC-2.06.001
//! Test vector: TV-BC-2.06.001 — valid demo prism.toml deserializes without error.

#![allow(clippy::unwrap_used)]
#![allow(non_snake_case)]

use prism_bin::credential_cli::generate_demo_prism_toml;

/// Red Gate test: BC-2.06.001 TOML config loading — demo prism.toml is schema-valid.
///
/// Drives `generate_demo_prism_toml()` and asserts the returned string deserializes
/// via the same `PrismConfig` deserializer that boot step 2 uses at runtime.
///
/// # Why this FAILS at Red Gate
///
/// `generate_demo_prism_toml()` contains `todo!()` in the stub phase. The test
/// panics on `generate_demo_prism_toml()` call before any assertion is reached.
///
/// # What the implementer must do to make this PASS
///
/// 1. Implement `generate_demo_prism_toml()` in `credential_cli.rs` to return a
///    valid TOML string.
/// 2. The TOML must deserialize via `toml::from_str::<prism_bin::boot::PrismConfig>()`.
/// 3. The TOML must include:
///    - `spec_dir` — path to demo sensor specs directory
///    - `state_dir` — path to demo RocksDB state directory
///    - `[[orgs]]` with `org_id` (UUID v7) and `org_slug = "demo-org"`
/// 4. The org_id MUST be a real UUID v7 (boot step 3 rejects non-v7 UUIDs).
///
/// # BC-2.06.001 postcondition tested
///
/// "All `[clients.{id}]` sections are deserialized into `ClientConfig` structs" —
/// more precisely for this test: the generated file is accepted by `PrismConfig`
/// without `PrismError::Config` (file not found / TOML syntax error / permission denied).
#[test]
fn test_BC_2_06_001_demo_setup_generates_valid_prism_toml() {
    // Step 1: Generate the demo prism.toml content via the testable seam.
    // FAILS at Red Gate: generate_demo_prism_toml() panics with todo!().
    let toml_content = generate_demo_prism_toml();

    // Step 2: Assert the content is non-empty.
    assert!(
        !toml_content.is_empty(),
        "generate_demo_prism_toml() must return a non-empty TOML string (BC-2.06.001)"
    );

    // Step 3: Assert the content deserializes via the canonical PrismConfig deserializer.
    // This is the exact code path used by boot step 2 (step2_load_config in boot.rs).
    // A deserialization error here means the demo prism.toml is not schema-valid —
    // which would cause `prism start` to fail at boot step 2 (exit 2).
    let config: prism_bin::boot::PrismConfig = toml::from_str(&toml_content)
        .expect("generate_demo_prism_toml() must produce a TOML string that deserializes via PrismConfig without error (BC-2.06.001 postcondition)");

    // Step 4: Assert the config has at least one org entry (boot step 3 requires this).
    // BC-2.21.001 EC-21-001-001: "Config must declare at least one org".
    assert!(
        !config.orgs.is_empty(),
        "demo prism.toml must declare at least one org (BC-2.21.001 EC-21-001-001); \
         got 0 orgs in deserialized PrismConfig"
    );

    // Step 5: Assert the first org has a non-empty org_slug and org_id.
    let demo_org = &config.orgs[0];
    assert!(
        !demo_org.org_slug.is_empty(),
        "demo org must have a non-empty org_slug (BC-2.21.001)"
    );
    assert!(
        !demo_org.org_id.is_empty(),
        "demo org must have a non-empty org_id (BC-2.21.001)"
    );

    // Step 6: Assert the org_id parses as a valid UUID v7.
    // Boot step 3 (step3_init_org_registry) rejects non-v7 UUIDs with
    // "must be a UUID v7 (time-ordered, version 7)" error (BC-2.21.001 EC-21-001-008).
    let parsed_uuid = uuid::Uuid::parse_str(&demo_org.org_id).unwrap_or_else(|e| {
        panic!(
            "demo org_id '{}' must be a valid UUID: {e} (BC-2.21.001)",
            demo_org.org_id
        )
    });
    assert_eq!(
        parsed_uuid.get_version(),
        Some(uuid::Version::SortRand),
        "demo org_id '{}' must be a UUID v7 (time-ordered, version 7); \
         got version {:?} — use uuid::Uuid::now_v7() (BC-2.21.001 EC-21-001-008)",
        demo_org.org_id,
        parsed_uuid.get_version()
    );

    // Step 7: Assert spec_dir is non-empty (boot step 4 requires it).
    assert!(
        !config.spec_dir.as_os_str().is_empty(),
        "demo prism.toml must declare a non-empty spec_dir (BC-2.06.001)"
    );

    // Step 8: Assert state_dir is non-empty (boot step 6 requires it for RocksDB).
    assert!(
        !config.state_dir.as_os_str().is_empty(),
        "demo prism.toml must declare a non-empty state_dir (BC-2.06.001)"
    );
}
