//! Tests for S-DEMO-003 AC-001 — BC-2.06.001 TOML config loading contract
//! and AC-009 — overlay TOML format emitted by demo-run.sh.
//!
//! # Contracts under test
//!
//! BC-2.06.001 postcondition: "All `[clients.{id}]` sections are deserialized into
//! `ClientConfig` structs" — i.e., the TOML config file generated by `demo-setup.sh`
//! MUST be accepted by the `PrismConfig` deserializer at startup without error.
//!
//! AC-001 of S-DEMO-003 (traces to BC-2.06.001): after `scripts/demo-setup.sh` runs,
//! the generated `~/.config/prism-demo/prism.toml` must be schema-valid and
//! deserializable via `toml::from_str::<PrismConfig>()`.
//!
//! AC-009 (F-HIGH-201): demo queries return data rows. Requires per-org overlay TOMLs
//! with `base_url = "http://127.0.0.1:<port>"` written by `demo-run.sh` after the DTU
//! server starts. `test_AC_009_demo_run_overlay_toml_format_parses_as_sensor_instance_overlay`
//! validates that the TOML format emitted by the Python snippet in `demo-run.sh` is
//! accepted by `SensorInstanceOverlay` — the exact type `OverlayLoader::load_overlays`
//! uses at boot step 4c (BC-2.06.012 postcondition).
//!
//! # Testable seam
//!
//! Rather than depending on `scripts/demo-setup.sh` (which does not exist during the
//! Red Gate phase), the test exercises `credential_cli::generate_demo_prism_toml()` —
//! a Rust helper function that returns the canonical demo `prism.toml` content.
//!
//! The test-writer's rationale for this seam choice:
//! 1. `demo-setup.sh` does not exist during the Red Gate phase. Running the script would
//!    produce a file-not-found error, not a meaningful assertion about the TOML contract.
//! 2. The Rust helper gives the implementer a clear, in-process unit that `demo-setup.sh`
//!    can mirror or invoke to generate `~/.config/prism-demo/prism.toml`.
//! 3. The test exercises the `PrismConfig` deserializer directly — exactly the code path
//!    that boot step 2 calls at runtime (BC-2.06.001 postcondition).
//!
//! # Red Gate requirement
//!
//! This test MUST FAIL before the implementer adds a real implementation to
//! `generate_demo_prism_toml()`. The current stub panics with `todo!()`.
//!
//! Story: S-DEMO-003 | BC: BC-2.06.001, BC-2.06.012
//! Test vector: TV-BC-2.06.001 — valid demo prism.toml deserializes without error.
//! Test vector: TV-AC-009 — demo-run.sh overlay TOML format parses as SensorInstanceOverlay.

#![allow(clippy::unwrap_used)]
#![allow(non_snake_case)]

use prism_bin::credential_cli::generate_demo_prism_toml;
use prism_spec_engine::overlay::SensorInstanceOverlay;

/// Red Gate test: BC-2.06.001 TOML config loading — demo prism.toml is schema-valid.
///
/// Drives `generate_demo_prism_toml()` and asserts the returned string deserializes
/// via the same `PrismConfig` deserializer that boot step 2 uses at runtime.
///
/// # Why this FAILS at Red Gate
///
/// `generate_demo_prism_toml()` contains `todo!()` in the stub phase. The test
/// panics on `generate_demo_prism_toml()` call before any assertion is reached.
///
/// # What the implementer must do to make this PASS
///
/// 1. Implement `generate_demo_prism_toml()` in `credential_cli.rs` to return a
///    valid TOML string.
/// 2. The TOML must deserialize via `toml::from_str::<prism_bin::boot::PrismConfig>()`.
/// 3. The TOML must include:
///    - `spec_dir` — path to demo sensor specs directory
///    - `state_dir` — path to demo RocksDB state directory
///    - `[[orgs]]` with `org_id` (UUID v7) and `org_slug = "demo-org"`
/// 4. The org_id MUST be a real UUID v7 (boot step 3 rejects non-v7 UUIDs).
///
/// # BC-2.06.001 postcondition tested
///
/// "All `[clients.{id}]` sections are deserialized into `ClientConfig` structs" —
/// more precisely for this test: the generated file is accepted by `PrismConfig`
/// without `PrismError::Config` (file not found / TOML syntax error / permission denied).
#[test]
fn test_BC_2_06_001_demo_setup_generates_valid_prism_toml() {
    // Step 1: Generate the demo prism.toml content via the testable seam.
    // FAILS at Red Gate: generate_demo_prism_toml() panics with todo!().
    let toml_content = generate_demo_prism_toml();

    // Step 2: Assert the content is non-empty.
    assert!(
        !toml_content.is_empty(),
        "generate_demo_prism_toml() must return a non-empty TOML string (BC-2.06.001)"
    );

    // Step 3: Assert the content deserializes via the canonical PrismConfig deserializer.
    // This is the exact code path used by boot step 2 (step2_load_config in boot.rs).
    // A deserialization error here means the demo prism.toml is not schema-valid —
    // which would cause `prism start` to fail at boot step 2 (exit 2).
    let config: prism_bin::boot::PrismConfig = toml::from_str(&toml_content)
        .expect("generate_demo_prism_toml() must produce a TOML string that deserializes via PrismConfig without error (BC-2.06.001 postcondition)");

    // Step 4: Assert the config has at least one org entry (boot step 3 requires this).
    // BC-2.21.001 EC-21-001-001: "Config must declare at least one org".
    assert!(
        !config.orgs.is_empty(),
        "demo prism.toml must declare at least one org (BC-2.21.001 EC-21-001-001); \
         got 0 orgs in deserialized PrismConfig"
    );

    // Step 5: Assert the first org has a non-empty org_slug and org_id.
    let demo_org = &config.orgs[0];
    assert!(
        !demo_org.org_slug.is_empty(),
        "demo org must have a non-empty org_slug (BC-2.21.001)"
    );
    assert!(
        !demo_org.org_id.is_empty(),
        "demo org must have a non-empty org_id (BC-2.21.001)"
    );

    // Step 6: Assert the org_id parses as a valid UUID v7.
    // Boot step 3 (step3_init_org_registry) rejects non-v7 UUIDs with
    // "must be a UUID v7 (time-ordered, version 7)" error (BC-2.21.001 EC-21-001-008).
    let parsed_uuid = uuid::Uuid::parse_str(&demo_org.org_id).unwrap_or_else(|e| {
        panic!(
            "demo org_id '{}' must be a valid UUID: {e} (BC-2.21.001)",
            demo_org.org_id
        )
    });
    assert_eq!(
        parsed_uuid.get_version(),
        Some(uuid::Version::SortRand),
        "demo org_id '{}' must be a UUID v7 (time-ordered, version 7); \
         got version {:?} — use uuid::Uuid::now_v7() (BC-2.21.001 EC-21-001-008)",
        demo_org.org_id,
        parsed_uuid.get_version()
    );

    // Step 7: Assert spec_dir is non-empty (boot step 4 requires it).
    assert!(
        !config.spec_dir.as_os_str().is_empty(),
        "demo prism.toml must declare a non-empty spec_dir (BC-2.06.001)"
    );

    // Step 8: Assert state_dir is non-empty (boot step 6 requires it for RocksDB).
    assert!(
        !config.state_dir.as_os_str().is_empty(),
        "demo prism.toml must declare a non-empty state_dir (BC-2.06.001)"
    );
}

/// AC-009 / BC-2.06.012: overlay TOML format emitted by demo-run.sh parses as SensorInstanceOverlay.
///
/// Validates that the Python snippet in `scripts/demo-run.sh` generates overlay TOML that is
/// accepted by `toml::from_str::<SensorInstanceOverlay>()` — the exact deserialization path
/// used by `OverlayLoader::load_overlays` at boot step 4c.
///
/// # What is tested
///
/// The demo-run.sh Python snippet generates TOML in this format for each sensor:
/// ```toml
/// # Per-org overlay for crowdstrike sensor — demo-org (DTU demo)
/// # BC-2.06.012 / ADR-029: scalar-only overlay; no schema fields.
/// # Generated by demo-run.sh after DTU server starts (ephemeral port).
/// extends     = "crowdstrike"
/// instance_id = "crowdstrike@demo-org"
/// base_url    = "http://127.0.0.1:54321"
/// ```
///
/// This test constructs the same format for each of the 4 demo sensors with a representative
/// ephemeral port and asserts:
/// 1. The TOML deserializes via `SensorInstanceOverlay` without error.
/// 2. `extends` matches the sensor id.
/// 3. `instance_id` matches `{sensor_id}@demo-org` (BC-2.06.012 INV-SCALAR-003).
/// 4. `base_url` is `Some("http://127.0.0.1:<port>")` — the DTU-bound URL.
///
/// # Why this test doesn't need a live DTU (SID-1 compliance)
///
/// The DTU server provides ephemeral ports at runtime; the format of the overlay TOML is
/// independent of which port is actually chosen. This test uses a fixed representative port
/// (54321) to exercise the parse path without any external dependency.
///
/// The `#[ignore]`'d E2E tests in `e2e_smoke.rs` exercise the full data path
/// (DTU server → overlay written by demo-run.sh → prism boots → query returns rows).
/// This unit test covers the overlay *format* contract (AC-009 testable seam, SID-1).
///
/// Story: S-DEMO-003 | BC: BC-2.06.012 / ADR-029 | AC: AC-009 (F-HIGH-201)
#[test]
fn test_AC_009_demo_run_overlay_toml_format_parses_as_sensor_instance_overlay() {
    const ORG_SLUG: &str = "demo-org";
    const DEMO_PORT: u16 = 54321;

    for sensor_id in ["crowdstrike", "armis", "claroty", "cyberint"] {
        let base_url = format!("http://127.0.0.1:{DEMO_PORT}");
        // This is the exact TOML format emitted by the Python snippet in demo-run.sh.
        let overlay_toml = format!(
            "# Per-org overlay for {sensor_id} sensor — {ORG_SLUG} (DTU demo)\n\
             # BC-2.06.012 / ADR-029: scalar-only overlay; no schema fields.\n\
             # Generated by demo-run.sh after DTU server starts (ephemeral port).\n\
             extends     = \"{sensor_id}\"\n\
             instance_id = \"{sensor_id}@{ORG_SLUG}\"\n\
             base_url    = \"{base_url}\"\n"
        );

        let overlay: SensorInstanceOverlay = toml::from_str(&overlay_toml).unwrap_or_else(|e| {
            panic!(
                "demo-run.sh overlay TOML for sensor '{sensor_id}' failed to parse as \
                 SensorInstanceOverlay: {e}\n\
                 TOML content:\n{overlay_toml}\n\
                 Fix the Python snippet in scripts/demo-run.sh to match BC-2.06.012 overlay format."
            )
        });

        // AC-009 postcondition 1: extends matches the sensor id.
        assert_eq!(
            overlay.extends, sensor_id,
            "overlay 'extends' must equal sensor_id '{sensor_id}' (BC-2.06.012)"
        );

        // AC-009 postcondition 2: instance_id matches {sensor_id}@{org_slug} (INV-SCALAR-003).
        let expected_instance_id = format!("{sensor_id}@{ORG_SLUG}");
        assert_eq!(
            overlay.instance_id, expected_instance_id,
            "overlay 'instance_id' must be '{expected_instance_id}' (BC-2.06.012 INV-SCALAR-003)"
        );

        // AC-009 postcondition 3: base_url is set to the DTU-bound URL.
        assert_eq!(
            overlay.base_url.as_deref(),
            Some(base_url.as_str()),
            "overlay 'base_url' must be '{base_url}' (F-HIGH-201: data path requires DTU port)"
        );
    }
}

/// F-HIGH-301: demo-run.sh printed start command must include all 4 base-url env vars.
///
/// At boot step 4a, `env_resolver.rs` resolves `${env.VAR}` tokens in sensor TYPE spec
/// `base_url` fields. If any of the 4 required vars is absent or empty, E-SPEC-024 fires
/// and the boot hard-aborts (exit 2) before step 4c overlay loading can replace base_url
/// with the DTU clone URL.
///
/// # What is tested
///
/// The `scripts/demo-run.sh` `echo` block prints the `prism start` command. This test
/// reads that script as a string and asserts the four required env-var assignments appear
/// in the printed command, with the exact values prescribed by the proven E2E harness
/// (`crates/prism-bin/tests/helpers/mod.rs`):
///
/// - `CROWDSTRIKE_BASE_URL=http://127.0.0.1`   (must satisfy SEC-003 allowlist check)
/// - `ARMIS_INSTANCE_URL=http://127.0.0.1`     (satisfies step-4a URL token resolution)
/// - `CLAROTY_INSTANCE_URL=http://127.0.0.1`   (satisfies step-4a URL token resolution)
/// - `CYBERINT_ENVIRONMENT=demo`               (interpolated into https://demo.cyberint.io)
///
/// # Why this is not an ignored integration test (SID-1 compliance)
///
/// A live DTU server is NOT required to verify that the script text contains the correct
/// env-var assignments. The testable seam is the script's printed output (a string-level
/// check). The full E2E boot path (DTU → overlay → query) is covered by `#[ignore]`'d
/// tests in `e2e_smoke.rs` (which require a live DTU server).
///
/// Story: S-DEMO-003 | AC: F-HIGH-301 (boot env vars) | SID-1 compliance
#[test]
fn test_F_HIGH_301_demo_run_sh_printed_start_command_includes_base_url_env_vars() {
    // Read the demo-run.sh script relative to CARGO_MANIFEST_DIR.
    // The script lives at <repo_root>/scripts/demo-run.sh.
    // CARGO_MANIFEST_DIR for prism-bin is <repo_root>/crates/prism-bin.
    let manifest_dir = std::path::Path::new(env!("CARGO_MANIFEST_DIR"));
    let repo_root = manifest_dir
        .parent()
        .expect("crates/prism-bin has a parent")
        .parent()
        .expect("crates has a parent (repo root)");
    let script_path = repo_root.join("scripts").join("demo-run.sh");

    let script_content = std::fs::read_to_string(&script_path).unwrap_or_else(|e| {
        panic!(
            "Could not read scripts/demo-run.sh at {}: {e}\n\
             This test verifies F-HIGH-301: the script must include the 4 base-url env vars.",
            script_path.display()
        )
    });

    // Assert each required env-var assignment appears verbatim in the script.
    // These are the exact values prescribed by the E2E harness (helpers/mod.rs).
    let required_env_assignments: &[(&str, &str)] = &[
        ("CROWDSTRIKE_BASE_URL", "http://127.0.0.1"),
        ("ARMIS_INSTANCE_URL", "http://127.0.0.1"),
        ("CLAROTY_INSTANCE_URL", "http://127.0.0.1"),
        ("CYBERINT_ENVIRONMENT", "demo"),
    ];

    for (var_name, expected_value) in required_env_assignments {
        let assignment = format!("{var_name}={expected_value}");
        assert!(
            script_content.contains(&assignment),
            "scripts/demo-run.sh must contain the env-var assignment '{assignment}' in the \
             printed prism start command.\n\
             Without this, boot step 4a (env_resolver.rs) fires E-SPEC-024 for the \
             '{var_name}' token in the sensor TYPE spec base_url, and prism hard-aborts \
             (exit 2) before step 4c overlay loading.\n\
             Fix: add '{assignment}' to the 'echo' block that prints the start command \
             (F-HIGH-301)."
        );
    }
}

/// AC-009 / F-HIGH-201: overlay base_url must use 127.0.0.1 (DTU bind address).
///
/// The DTU demo server always binds to 127.0.0.1 (demo.toml: bind = "127.0.0.1").
/// The overlay `base_url` must start with "http://127.0.0.1:" so that prism routes
/// fetch requests to the local DTU clone. A `localhost` URL would also work but
/// demo.toml uses 127.0.0.1, so this test enforces the correct bind address.
///
/// Story: S-DEMO-003 | BC: BC-2.06.012 | AC: AC-009 (F-HIGH-201)
#[test]
fn test_AC_009_demo_overlay_base_url_uses_loopback_bind_address() {
    const ORG_SLUG: &str = "demo-org";
    // Use a representative port; the exact value does not matter for this format check.
    const DEMO_PORT: u16 = 12345;

    for sensor_id in ["crowdstrike", "armis", "claroty", "cyberint"] {
        let base_url = format!("http://127.0.0.1:{DEMO_PORT}");
        let overlay_toml = format!(
            "extends     = \"{sensor_id}\"\n\
             instance_id = \"{sensor_id}@{ORG_SLUG}\"\n\
             base_url    = \"{base_url}\"\n"
        );

        let overlay: SensorInstanceOverlay = toml::from_str(&overlay_toml)
            .expect("overlay TOML must parse as SensorInstanceOverlay");

        let url = overlay
            .base_url
            .as_deref()
            .expect("base_url must be Some (F-HIGH-201)");
        assert!(
            url.starts_with("http://127.0.0.1:"),
            "overlay base_url must use the DTU bind address 'http://127.0.0.1:' \
             (demo.toml bind = \"127.0.0.1\"); got '{url}'"
        );
    }
}
