//! OCSF protobuf `DescriptorPool` singleton.
//!
//! BC-2.02.001 postcondition: all 83 OCSF v1.x event class descriptors are available
//! as protobuf message descriptors at runtime, loaded from the compile-time binary
//! emitted by `ocsf-proto-gen` + `prost-build`.
//!
//! # Architecture Compliance
//!
//! - MUST use `OnceLock<DescriptorPool>` — never `Mutex<Option<...>>`.
//!   (S-1.04 Architecture Compliance Rules)
//! - `OcsfDescriptors::get()` is the only public access path.
//! - Initialization failure panics — this is a boot-time invariant; the binary cannot
//!   function without the pool. (S-1.04 Edge Cases: DescriptorPool initialization failure)
//!
//! # Stub Status
//!
//! The `OCSF_DESCRIPTOR_BYTES` constant is a zero-byte placeholder emitted by the
//! stub `build.rs`. When `ocsf-proto-gen` is available, `build.rs` will write a
//! real `FileDescriptorSet` binary to `OUT_DIR/ocsf_descriptor.bin` and the pool
//! will be populated with actual OCSF descriptors.

use prost_reflect::DescriptorPool;
use std::sync::OnceLock;

/// Binary `FileDescriptorSet` generated by `prost-build` from ocsf-proto-gen output.
///
/// STUB: Currently zero bytes — populated by real build.rs after ocsf-proto-gen lands.
static OCSF_DESCRIPTOR_BYTES: &[u8] =
    include_bytes!(concat!(env!("OUT_DIR"), "/ocsf_descriptor.bin"));

/// Singleton handle for the OCSF protobuf descriptor pool.
///
/// Provides access to descriptors for all 83 OCSF v1.x event classes compiled at
/// build time. (BC-2.02.001)
pub struct OcsfDescriptors;

static POOL: OnceLock<DescriptorPool> = OnceLock::new();

impl OcsfDescriptors {
    /// Returns a reference to the global OCSF `DescriptorPool`.
    ///
    /// The pool is initialized exactly once on first call. Initialization failure
    /// panics — it is a boot-time invariant that is not recoverable. (S-1.04 Edge Cases)
    ///
    /// # Panics
    ///
    /// Panics if the compiled descriptor bytes are invalid. This can only happen if
    /// `build.rs` produced malformed output — which is a build-time bug, not a runtime
    /// condition.
    pub fn get() -> &'static DescriptorPool {
        POOL.get_or_init(|| {
            // STUB: OCSF_DESCRIPTOR_BYTES is empty — DescriptorPool::decode() on empty
            // bytes returns an empty pool, not an error. Tests that query the pool for
            // specific OCSF class descriptors will fail (Red Gate), as required.
            DescriptorPool::decode(OCSF_DESCRIPTOR_BYTES)
                .expect("OCSF descriptor pool initialization failed — this is a build-time bug")
        })
    }
}
