// Stub phase: host module functions are declared but not yet called from production code.
// dead_code is expected during the stub — all functions will be wired in Task 4/5.
#![allow(dead_code)]
//! CrowdStrike OAuth2 client-credentials plugin — in-repo .prx WASM guest.
//!
//! Story: PLUGIN-MIGRATION-001-E
//! BCs: BC-2.01.016, BC-2.17.001, BC-2.17.006, BC-2.17.007, BC-2.16.013
//!
//! This plugin replaces `crates/prism-sensors/src/auth/crowdstrike.rs`
//! (CrowdStrikeAuth + token acquisition logic) with a WASM Component that
//! the PluginRuntime loads at boot step 7.5 (BC-2.22.001).
//!
//! Credential handling per AD-017 (AI-opaque model):
//!   - The WASM guest NEVER holds the raw client_secret.
//!   - credential_handle is an opaque string passed to host functions.
//!   - host::http-request injects the resolved secret into the POST body.
//!   - guest only sees access_token (non-sensitive bearer token for the session).
//!
//! KV store keys (scoped by plugin_id automatically by PluginKvStore::set):
//!   "token"           — cached bearer token string
//!   "expires_at_secs" — Unix timestamp string (u64) after which cache is stale
//!
//! TTL: expires_in_seconds - 30 seconds (matching CachedToken::is_valid semantics
//!   from the legacy CrowdStrikeAdapter; RFC 6749 early-expiry recommendation).

// ---------------------------------------------------------------------------
// Auth error type
// ---------------------------------------------------------------------------

/// Errors returned by acquire_token and get_token.
///
/// Traces to: BC-2.01.016 §error cases; AC-001 error-path coverage.
/// `#[non_exhaustive]` per CLAUDE.md conventions — public enum.
#[non_exhaustive]
#[derive(Debug)]
pub enum AuthError {
    /// POST /oauth2/token returned 4xx with invalid credentials.
    ///
    /// Maps to PipelineExecutor propagating SpecEngineError::AuthRefreshFailed.
    InvalidCredentials,
    /// Token response body was not valid JSON or missing required fields.
    ///
    /// Detail string contains the parse failure reason (not the token value).
    ResponseParse(String),
    /// KV store size limit exceeded or other internal failure.
    ///
    /// Detail string describes the internal error (not credential data).
    Internal(String),
}

impl std::fmt::Display for AuthError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            AuthError::InvalidCredentials => write!(f, "invalid client credentials"),
            AuthError::ResponseParse(detail) => write!(f, "token response parse error: {detail}"),
            AuthError::Internal(detail) => write!(f, "internal auth error: {detail}"),
        }
    }
}

// ---------------------------------------------------------------------------
// Host function declarations (imported from the host runtime)
// ---------------------------------------------------------------------------

/// Host-provided HTTP response type.
///
/// Mirrors the WIT http-response record: `{ status: u16, headers: list<(string,string)>, body: list<u8> }`.
/// This is a guest-side representation — actual WASM ABI wiring happens via WIT bindgen.
#[derive(Debug)]
pub struct HttpResponse {
    pub status: u16,
    pub body: Vec<u8>,
}

/// Guest-side declarations of host functions.
///
/// In a compiled WASM Component these would be generated by `wit-bindgen`.
/// For the stub phase, they are declared as extern functions that `todo!()` will never reach.
///
/// Implements: host::http-request, host::kv-get, host::kv-set, host::log host functions
/// registered in `host_functions.rs::register_host_functions`.
mod host {
    use super::HttpResponse;

    /// Call host::http-request — outbound HTTP via allowlisted reqwest::Client.
    ///
    /// URL host must be in plugin's allowed_urls (enforced by host, not guest).
    /// 30-second timeout enforced by the shared client (PLUGIN_HTTP_CLIENT_TIMEOUT_SECS).
    pub fn http_request(
        _method: &str,
        _url: &str,
        _headers: Vec<(String, String)>,
        _body: Option<Vec<u8>>,
    ) -> HttpResponse {
        todo!("PLUGIN-MIGRATION-001-E: host::http-request — wired during Task 4 implementation")
    }

    /// Call host::kv-get — read a value from the scoped KV store.
    ///
    /// Key is automatically scoped to `"crowdstrike-oauth2:{key}"` by the host.
    pub fn kv_get(_key: &str) -> Option<String> {
        todo!("PLUGIN-MIGRATION-001-E: host::kv-get — wired during Task 5 implementation")
    }

    /// Call host::kv-set — write a value to the scoped KV store.
    ///
    /// Returns Err(message) if the 1MB per-plugin KV size limit is exceeded (E-PLUGIN-003).
    pub fn kv_set(_key: &str, _value: &str) -> Result<(), String> {
        todo!("PLUGIN-MIGRATION-001-E: host::kv-set — wired during Task 5 implementation")
    }

    /// Call host::log — forward message to the host's tracing subscriber.
    pub fn log(_level: &str, _message: &str) {
        todo!("PLUGIN-MIGRATION-001-E: host::log — wired during Task 4 implementation")
    }
}

// ---------------------------------------------------------------------------
// SensorAuth WIT interface exports (sensor-auth interface)
// ---------------------------------------------------------------------------

/// Return the canonical auth type name for this plugin.
///
/// MUST return `"oauth2_client_credentials"` per INV-AUTH-OPEN-003 Rule A
/// (BC-2.01.016). This value is matched against `crowdstrike.sensor.toml`
/// `auth_type` field at spec-load time (ADR-028 §D2 LOCKED value).
///
/// AC-002 Red Gate Test 2 drives this function.
///
/// # Example (post-implementation)
/// ```ignore
/// assert_eq!(auth_type_name(), "oauth2_client_credentials");
/// ```
pub fn auth_type_name() -> &'static str {
    todo!("PLUGIN-MIGRATION-001-E: auth_type_name() — implement in Task 4")
}

/// Force-acquire a fresh OAuth2 token by calling POST /oauth2/token.
///
/// This is the FORCED-REFRESH entrypoint — it MUST bypass the KV cache and
/// always issue a new token request regardless of cache state. Called by
/// `PipelineExecutor::issue_request_with_retry` on HTTP 401 (VP-150).
///
/// Steps (AC-003, AC-006):
///   1. Call host::http-request POST to the OAuth2 token endpoint.
///   2. Parse access_token + expires_in from the JSON response.
///   3. Cache the new token in PluginKvStore via host::kv-set.
///   4. Return Ok(access_token).
///
/// Error cases:
///   - 401 response → AuthError::InvalidCredentials (EC-001).
///   - Non-JSON or missing access_token → AuthError::ResponseParse (EC-002, EC-003).
///   - expires_in missing or zero → default TTL 1799s per CrowdStrikeAdapter::acquire_token
///     `unwrap_or(1799)` semantics (EC-004).
///   - KV store full → AuthError::Internal("kv_store size limit exceeded") (EC-005).
///
/// Security invariant (AD-017): credential_handle is opaque. The raw client_secret
/// is NEVER stored in guest WASM memory — the host resolves the handle and injects
/// the secret into the POST body via host::http-request credential-handle substitution.
///
/// AC-003 Red Gate Test 3 / AC-006 Red Gate Test 6 drive this function.
pub fn acquire_token(_credential_handle: &str) -> Result<String, AuthError> {
    todo!("PLUGIN-MIGRATION-001-E: acquire_token() — implement in Task 4")
}

/// Get a cached token, or acquire a fresh one if the cache is stale.
///
/// Steps (AC-004, AC-005):
///   1. Read expires_at_secs from KV via host::kv-get("expires_at_secs").
///   2. If present and current_time_secs() < expires_at_secs → return cached token.
///   3. Otherwise → fall through to acquire_token(credential_handle).
///
/// TTL check: expires_at_secs was written as `token_issue_unix + expires_in - 30`.
/// The 30-second buffer matches CachedToken::is_valid() semantics in the legacy adapter.
///
/// OQ-2 note: host_current_time_secs() host function existence is unconfirmed.
/// If absent, implementer adds the host function in scope (Known Gap in story).
///
/// AC-004 Red Gate Test 4 / AC-005 Red Gate Test 5 drive this function.
pub fn get_token(_credential_handle: &str) -> Result<String, AuthError> {
    todo!("PLUGIN-MIGRATION-001-E: get_token() — implement in Task 5")
}

// ---------------------------------------------------------------------------
// WASM export entrypoints (called by the host via WIT dispatch)
// ---------------------------------------------------------------------------

/// WASM export: `auth-type-name` (WIT sensor-auth interface).
///
/// The host's PluginRuntime dispatches to this export when calling
/// `call_auth_type_name()` (or equivalent WIT call path).
///
/// AC-002: must return "oauth2_client_credentials".
#[unsafe(no_mangle)]
pub extern "C" fn auth_type_name_export() -> *const u8 {
    todo!("PLUGIN-MIGRATION-001-E: auth-type-name export — wired via WIT bindgen in Task 4")
}

/// WASM export: `acquire-token` (WIT sensor-auth interface).
///
/// Called by the host on 401 retry path (VP-150 end-to-end).
/// Must bypass KV cache — always force a fresh POST /oauth2/token.
#[unsafe(no_mangle)]
pub extern "C" fn acquire_token_export(_ptr: *const u8, _len: usize) -> u64 {
    todo!("PLUGIN-MIGRATION-001-E: acquire-token export — wired via WIT bindgen in Task 4")
}

/// WASM export: `get-token` (WIT sensor-auth interface).
///
/// Called by the host on pre-request token lookup (cache-first path).
#[unsafe(no_mangle)]
pub extern "C" fn get_token_export(_ptr: *const u8, _len: usize) -> u64 {
    todo!("PLUGIN-MIGRATION-001-E: get-token export — wired via WIT bindgen in Task 5")
}

// ---------------------------------------------------------------------------
// WAT-compatible exports for WIT validation compatibility
// ---------------------------------------------------------------------------
// NOTE: These are stub exports that satisfy the plugin discovery WIT validation
// used by prism-spec-engine tests (which use WAT-based plugin fixtures).
// The actual WIT bindgen exports above replace these in the compiled Component.
// During the stub phase, these allow `cargo check` to pass without full WIT bindgen.

/// Required WIT export: `name` — returns plugin identity string.
///
/// Used by PluginRuntime::load_plugin → discovery::validate_wit_interface.
/// Returns "crowdstrike-oauth2" (must match plugin_id in plugin.toml).
pub fn plugin_name() -> &'static str {
    "crowdstrike-oauth2"
}

/// Required WIT export: `version` — returns plugin semver string.
///
/// Used by PluginRuntime::load_plugin → discovery::validate_wit_interface.
pub fn plugin_version() -> &'static str {
    "0.1.0"
}
