//! CrowdStrike OAuth2 client-credentials plugin — in-repo .prx WASM guest.
//!
//! Story: PLUGIN-MIGRATION-001-E
//! BCs: BC-2.01.016, BC-2.17.001, BC-2.17.006, BC-2.17.007, BC-2.16.013
//!
//! This plugin replaces `crates/prism-sensors/src/auth/crowdstrike.rs`
//! (CrowdStrikeAuth + token acquisition logic) with a WASM Component that
//! the PluginRuntime loads at boot step 7.5 (BC-2.22.001).
//!
//! ## Architecture
//!
//! In WASM target (`wasm32-wasip1` / `wasm32-unknown-unknown`):
//!   - Host functions are imported via `wit_bindgen::generate!` macro-generated bindings
//!     derived from `wit/sensor-auth.wit`. This ensures Component Model ABI alignment.
//!   - The Component Model ABI wires these at instantiation time from the registered
//!     linker functions in `host_functions.rs::register_host_functions`.
//!
//! In native lib target (cargo check / cargo test on host):
//!   - `#[cfg(not(target_arch = "wasm32"))]` gates stub implementations that allow
//!     `cargo check --target <native>` to succeed without linker errors.
//!   - The native stubs are gated under `#[cfg(test)]` proving non-production-reachability
//!     (F-LP2-HIGH-004 closure). Tests use WAT fixtures, not this native lib.
//!
//! ## Credential Handling (AD-017)
//!
//! The WASM guest NEVER holds the raw client_secret. The `credential_handle` passed to
//! `acquire_token` / `get_token` is an opaque string. In the test path, `credential_handle`
//! encodes `client_id` + `client_secret` directly in the form body (since DTU clones do not
//! enforce credential security). In production, the host resolves the handle to credentials
//! via the keyring and injects the form body via `host_http_request` credential substitution.
//!
//! KV store keys (scoped by plugin_id automatically by PluginKvStore::set):
//!   "token"           — cached bearer token string
//!   "expires_at_secs" — Unix timestamp string (u64) after which cache is stale
//!   "token_endpoint"  — OAuth2 token endpoint URL (set in config by make_host_state)
//!
//! TTL: expires_in_seconds - 30 seconds (matching CachedToken::is_valid semantics
//!   from the legacy CrowdStrikeAdapter; RFC 6749 early-expiry recommendation).

// ---------------------------------------------------------------------------
// Auth error type
// ---------------------------------------------------------------------------

/// Errors returned by acquire_token and get_token.
///
/// Traces to: BC-2.01.016 §error cases; AC-001 error-path coverage.
/// `#[non_exhaustive]` per CLAUDE.md conventions — public enum.
#[non_exhaustive]
#[derive(Debug)]
pub enum AuthError {
    /// POST /oauth2/token returned 4xx with invalid credentials.
    ///
    /// Maps to PipelineExecutor propagating SpecEngineError::AuthRefreshFailed.
    InvalidCredentials,
    /// Token response body was not valid JSON or missing required fields.
    ///
    /// Detail string contains the parse failure reason (not the token value).
    ResponseParse(String),
    /// KV store size limit exceeded or other internal failure.
    ///
    /// Detail string describes the internal error (not credential data).
    Internal(String),
}

impl std::fmt::Display for AuthError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            AuthError::InvalidCredentials => write!(f, "invalid client credentials"),
            AuthError::ResponseParse(detail) => write!(f, "token response parse error: {detail}"),
            AuthError::Internal(detail) => write!(f, "internal auth error: {detail}"),
        }
    }
}

// ---------------------------------------------------------------------------
// HTTP response type
// ---------------------------------------------------------------------------

/// HTTP response type returned by host::http-request.
///
/// Mirrors the WIT `http-response` record (F-LP2-HIGH-002). `#[non_exhaustive]`
/// per CLAUDE.md conventions (F-LP1-HIGH-005 closure).
#[non_exhaustive]
#[derive(Debug)]
pub struct HttpResponse {
    pub status: u16,
    pub body: Vec<u8>,
}

// ---------------------------------------------------------------------------
// Host function implementations
//
// WASM target: generated by wit_bindgen::generate! from wit/sensor-auth.wit.
//   This replaces the prior manual #[link(wasm_import_module = "host")] extern
//   blocks with type-safe macro-generated bindings (F-LP2-HIGH-002 closure).
//   Component Model ABI is generated from the WIT spec — no manual encoding.
//
// Native target (cargo check / cargo test on host): gated under #[cfg(test)]
//   to prove these stubs are NOT production-reachable (F-LP2-HIGH-004 closure).
//   Tests use WAT fixtures, not this native lib build.
// ---------------------------------------------------------------------------

/// WASM target: wit-bindgen-generated host function bindings AND Component Model export wiring.
///
/// The `wit_bindgen::generate!` macro reads `wit/sensor-auth.wit` and generates:
/// - Safe Rust wrappers for all host-imported functions (http-request, kv-get,
///   kv-set, current-time-secs, get-config, log)
/// - The Component Model ABI — no manual (status << 32 | len) encoding
/// - The `exports::prism::crowdstrike_oauth2::sensor_auth::Guest` trait that the
///   plugin must implement (F-LP3-HIGH-001 closure: was missing, causing WIT
///   validation failure in `validate_wit_interface` — kebab-case exports absent)
///
/// F-LP2-HIGH-002 closure: replaces the prior manual #[link] extern "C" blocks.
/// F-LP3-HIGH-001 closure: adds `impl Guest for Component` + `export!(Component)`.
#[cfg(target_arch = "wasm32")]
mod host_impl {
    use super::AuthError;
    use super::HttpResponse;

    // wit-bindgen generates host function wrappers AND export trait from the WIT spec.
    // The generated code is placed at the current module scope.
    wit_bindgen::generate!({
        world: "crowdstrike-oauth2",
        path: "wit/sensor-auth.wit",
    });

    /// Issue POST via the wit-bindgen-generated host::http-request.
    ///
    /// Token endpoint is the URL; body is the OAuth2 form-encoded credentials.
    pub fn http_request(method: &str, url: &str, body: &[u8]) -> HttpResponse {
        // wit-bindgen generates prism::crowdstrike_oauth2::host::http_request.
        // The WIT interface takes method, url, headers, body: option<list<u8>>.
        let response = prism::crowdstrike_oauth2::host::http_request(
            method,
            url,
            &[], // no extra headers for OAuth2 token endpoint (form body is self-describing)
            Some(body),
        );
        HttpResponse {
            status: response.status,
            body: response.body,
        }
    }

    /// Read from host::kv-get. Returns None if key not present.
    pub fn kv_get(key: &str) -> Option<String> {
        prism::crowdstrike_oauth2::host::kv_get(key)
    }

    /// Write to host::kv-set. Returns Err(msg) if KV limit exceeded.
    pub fn kv_set(key: &str, value: &str) -> Result<(), String> {
        prism::crowdstrike_oauth2::host::kv_set(key, value).map_err(|e| e)
    }

    /// Get current wall-clock time as Unix seconds.
    pub fn current_time_secs() -> u64 {
        prism::crowdstrike_oauth2::host::current_time_secs()
    }

    /// Read a config value from the host config map.
    pub fn get_config(key: &str) -> Option<String> {
        prism::crowdstrike_oauth2::host::get_config(key)
    }

    /// Convert our crate-level `AuthError` to the wit-bindgen-generated
    /// `exports::prism::crowdstrike_oauth2::sensor_auth::AuthError` variant.
    fn to_wit_auth_error(
        e: AuthError,
    ) -> exports::prism::crowdstrike_oauth2::sensor_auth::AuthError {
        use exports::prism::crowdstrike_oauth2::sensor_auth::AuthError as WitAuthError;
        match e {
            AuthError::InvalidCredentials => WitAuthError::InvalidCredentials,
            AuthError::ResponseParse(msg) => WitAuthError::ResponseParse(msg),
            AuthError::Internal(msg) => WitAuthError::Internal(msg),
        }
    }

    /// Component Model export implementation.
    ///
    /// F-LP3-HIGH-001 closure: `wit_bindgen::generate!` with `export sensor-auth` in the WIT
    /// world generates an `exports::prism::crowdstrike_oauth2::sensor_auth::Guest` trait.
    /// The plugin MUST implement this trait and register via `export!(Component)` so that
    /// wit-bindgen emits the properly named kebab-case WIT exports (`auth-type-name`,
    /// `acquire-token`, `get-token`) instead of the hand-rolled snake_case `*_export`
    /// wrappers that compile to the wrong export names and fail `validate_wit_interface`.
    ///
    /// Production caller: `PluginRuntime::dispatch_plugin_acquire_token` (mod.rs:720)
    /// which calls `get_func(&mut store, "acquire-token")` — the kebab-case name is
    /// required for this lookup to succeed on the Component Model path.
    struct Component;

    impl exports::prism::crowdstrike_oauth2::sensor_auth::Guest for Component {
        /// Return the canonical auth type name.
        ///
        /// MUST return "oauth2_client_credentials" per INV-AUTH-OPEN-003 Rule A (BC-2.01.016).
        fn auth_type_name() -> String {
            super::auth_type_name().to_string()
        }

        /// Force-acquire a fresh OAuth2 token (bypass KV cache).
        ///
        /// Reads `token_endpoint` from host config map (`get-config("token_endpoint")`),
        /// then delegates to `super::acquire_token`. The WIT interface takes only
        /// `credential-handle` (not `token_endpoint` directly); the endpoint is
        /// configuration-managed by the host per the plugin config map.
        ///
        /// EC-006: absent `token_endpoint` in config → `AuthError::Internal`.
        fn acquire_token(
            credential_handle: String,
        ) -> Result<String, exports::prism::crowdstrike_oauth2::sensor_auth::AuthError> {
            let token_endpoint = get_config("token_endpoint").ok_or_else(|| {
                to_wit_auth_error(AuthError::Internal(
                    "token_endpoint absent from host config (EC-006)".to_string(),
                ))
            })?;
            super::acquire_token(&credential_handle, &token_endpoint).map_err(to_wit_auth_error)
        }

        /// Get a cached or freshly-acquired token.
        ///
        /// Reads `token_endpoint` from host config map (`get-config("token_endpoint")`),
        /// then delegates to `super::get_token`.
        fn get_token(
            credential_handle: String,
        ) -> Result<String, exports::prism::crowdstrike_oauth2::sensor_auth::AuthError> {
            let token_endpoint = get_config("token_endpoint").ok_or_else(|| {
                to_wit_auth_error(AuthError::Internal(
                    "token_endpoint absent from host config (EC-006)".to_string(),
                ))
            })?;
            super::get_token(&credential_handle, &token_endpoint).map_err(to_wit_auth_error)
        }
    }

    // Register Component as the export implementation.
    // wit-bindgen emits properly named kebab-case WIT export symbols:
    //   auth-type-name, acquire-token, get-token
    // These are the names that PluginRuntime::dispatch_plugin_acquire_token looks up
    // via get_func(&mut store, "acquire-token") on the Component Model path.
    export!(Component);
}

/// Native target: stub implementations gated under `#[cfg(test)]` to prove
/// these stubs are NOT production-reachable in native builds (F-LP2-HIGH-004 closure).
///
/// Tests use WAT fixtures (not this native lib); these stubs exist only to allow
/// the `#[cfg(test)]` functions that call host_impl to compile on native targets.
/// Any non-test, non-WASM caller would fail to compile (module not defined) —
/// proving that the `acquire_token` / `get_token` logic is only compiled for:
///   - wasm32 targets (production Component), OR
///   - test builds (via `#[cfg(test)]` gate on the calling functions)
#[cfg(all(not(target_arch = "wasm32"), test))]
mod host_impl {
    use super::HttpResponse;

    pub fn http_request(_method: &str, _url: &str, _body: &[u8]) -> HttpResponse {
        panic!(
            "host::http_request called in native build — use WAT fixture in tests, \
             compile to wasm32-wasip1 for production use"
        )
    }

    pub fn kv_get(_key: &str) -> Option<String> {
        panic!(
            "host::kv_get called in native build — use WAT fixture in tests, \
             compile to wasm32-wasip1 for production use"
        )
    }

    pub fn kv_set(_key: &str, _value: &str) -> Result<(), String> {
        panic!(
            "host::kv_set called in native build — use WAT fixture in tests, \
             compile to wasm32-wasip1 for production use"
        )
    }

    pub fn current_time_secs() -> u64 {
        panic!(
            "host::current_time_secs called in native build — use WAT fixture in tests, \
             compile to wasm32-wasip1 for production use"
        )
    }

    pub fn get_config(_key: &str) -> Option<String> {
        panic!(
            "host::get_config called in native build — use WAT fixture in tests, \
             compile to wasm32-wasip1 for production use"
        )
    }
}

// ---------------------------------------------------------------------------
// SensorAuth WIT interface exports (sensor-auth interface)
// ---------------------------------------------------------------------------

/// Return the canonical auth type name for this plugin.
///
/// MUST return `"oauth2_client_credentials"` per INV-AUTH-OPEN-003 Rule A
/// (BC-2.01.016). This value is matched against `crowdstrike.sensor.toml`
/// `auth_type` field at spec-load time (ADR-028 §D2 LOCKED value).
///
/// AC-002 Red Gate Test 2 drives this function.
///
/// # Example
/// ```
/// use crowdstrike_oauth2_plugin::auth_type_name;
/// assert_eq!(auth_type_name(), "oauth2_client_credentials");
/// ```
pub fn auth_type_name() -> &'static str {
    "oauth2_client_credentials"
}

/// Force-acquire a fresh OAuth2 token by calling POST /oauth2/token.
///
/// Gated under `#[cfg(any(target_arch = "wasm32", test))]`:
/// - On wasm32: production path via wit-bindgen-generated host function bindings.
/// - On native: only accessible from tests (WAT fixture tests that provide host_impl stubs).
/// - On non-wasm, non-test: not compiled — `cargo check` does not include this function,
///   proving it is NOT production-reachable in native builds (F-LP2-HIGH-004).
///
/// This is the FORCED-REFRESH entrypoint — it MUST bypass the KV cache and
/// always issue a new token request regardless of cache state. Called by
/// `PipelineExecutor::issue_request_with_retry` on HTTP 401 (VP-150).
///
/// Steps (AC-003, AC-006):
///   1. Read token_endpoint from host config map via host::get-config("token_endpoint").
///   2. Call host::http-request POST to the OAuth2 token endpoint.
///   3. Parse access_token + expires_in from the JSON response.
///   4. Cache the new token in PluginKvStore via host::kv-set.
///   5. Return Ok(access_token).
///
/// Error cases:
///   - 401 response → AuthError::InvalidCredentials (EC-001).
///   - Non-JSON or missing access_token → AuthError::ResponseParse (EC-002, EC-003).
///   - expires_in missing or zero → default TTL 1799s per CrowdStrikeAdapter::acquire_token
///     `unwrap_or(1799)` semantics (EC-004).
///   - KV store full → AuthError::Internal("kv_store size limit exceeded") (EC-005).
///   - token_endpoint absent from config → AuthError::Internal (EC-006, config gap).
///
/// Security invariant (AD-017): credential_handle is opaque. The raw client_secret
/// is NEVER stored in guest WASM memory — the host resolves the handle and injects
/// the secret into the POST body via host::http-request credential-handle substitution.
///
/// AC-003 Red Gate Test 3 / AC-006 Red Gate Test 6 drive this function.
#[cfg(any(target_arch = "wasm32", test))]
pub fn acquire_token(credential_handle: &str, token_endpoint: &str) -> Result<String, AuthError> {
    // Build form body. In production, the host resolves the credential_handle
    // to client_id + client_secret. In test DTU paths, the credential_handle
    // encodes "client_id=<id>&client_secret=<secret>" directly.
    let form_body = format!("{}&grant_type=client_credentials", credential_handle);

    // Issue POST /oauth2/token via host::http-request (wit-bindgen generated).
    let response = host_impl::http_request("POST", token_endpoint, form_body.as_bytes());

    // 401 → invalid credentials (EC-001).
    if response.status == 401 {
        return Err(AuthError::InvalidCredentials);
    }

    // Non-2xx → parse error (EC-002).
    if response.status < 200 || response.status >= 300 {
        return Err(AuthError::ResponseParse(format!(
            "token endpoint returned HTTP {}",
            response.status
        )));
    }

    // Parse JSON body for access_token + expires_in.
    // F-LP2-HIGH-005 closure: use checked from_utf8 (not unchecked) — defense-in-depth.
    let body_str = std::str::from_utf8(&response.body)
        .map_err(|e| AuthError::ResponseParse(format!("invalid UTF-8 in response body: {e}")))?;

    let json: serde_json::Value =
        serde_json::from_str(body_str).map_err(|e| AuthError::ResponseParse(e.to_string()))?;

    let access_token = json
        .get("access_token")
        .and_then(|v| v.as_str())
        .ok_or_else(|| AuthError::ResponseParse("missing access_token field".to_string()))?
        .to_string();

    // expires_in: default 1799s when missing or zero (EC-004 — matches CrowdStrikeAdapter semantics).
    let expires_in: u64 = json
        .get("expires_in")
        .and_then(|v| v.as_u64())
        .filter(|&v| v > 0)
        .unwrap_or(1799);

    // Compute expires_at = now + expires_in - 30s buffer (CachedToken::is_valid semantics).
    let now = host_impl::current_time_secs();
    let expires_at = now + expires_in.saturating_sub(30);

    // Cache token + expiry in KV store.
    host_impl::kv_set("token", &access_token).map_err(AuthError::Internal)?;
    host_impl::kv_set("expires_at_secs", &expires_at.to_string()).map_err(AuthError::Internal)?;

    Ok(access_token)
}

/// Get a cached token, or acquire a fresh one if the cache is stale.
///
/// Steps (AC-004, AC-005):
///   1. Read expires_at_secs from KV via host::kv-get("expires_at_secs").
///   2. If present and current_time_secs() < expires_at_secs → return cached token.
///   3. Otherwise → fall through to acquire_token(credential_handle, token_endpoint).
///
/// TTL check: expires_at_secs was written as `token_issue_unix + expires_in - 30`.
/// The 30-second buffer matches CachedToken::is_valid() semantics in the legacy adapter.
///
/// AC-004 Red Gate Test 4 / AC-005 Red Gate Test 5 drive this function.
#[cfg(any(target_arch = "wasm32", test))]
pub fn get_token(credential_handle: &str, token_endpoint: &str) -> Result<String, AuthError> {
    // Step 1: Check cache validity.
    let now = host_impl::current_time_secs();

    if let Some(expires_at_str) = host_impl::kv_get("expires_at_secs")
        && let Ok(expires_at) = expires_at_str.parse::<u64>()
        && now < expires_at
    {
        // Cache hit — return cached token if available.
        if let Some(cached_token) = host_impl::kv_get("token")
            && !cached_token.is_empty()
        {
            return Ok(cached_token);
        }
    }

    // Cache miss or stale — acquire fresh token.
    acquire_token(credential_handle, token_endpoint)
}

// ---------------------------------------------------------------------------
// WASM export entrypoints
//
// F-LP3-HIGH-001 closure: The prior hand-rolled `*_export` functions (auth_type_name_export,
// acquire_token_export, get_token_export) compiled to snake_case WASM export names, which
// do NOT match the kebab-case names required by `validate_wit_interface` (discovery.rs:26):
//   SENSOR_AUTH_REQUIRED_EXPORTS = ["auth-type-name", "acquire-token", "get-token"]
//
// These hand-rolled wrappers are DELETED. The WIT exports are now generated by
// `wit_bindgen::generate!` + `impl Guest for Component` + `export!(Component)` inside
// `host_impl` (see above). wit-bindgen emits properly named kebab-case WASM export symbols.
//
// Production callers:
//   - PluginRuntime::dispatch_plugin_acquire_token (mod.rs:720): get_func(&mut store, "acquire-token")
//   - PluginRuntime::load_plugin (mod.rs:208): validate_wit_interface checks all 3 exports
// ---------------------------------------------------------------------------

// ---------------------------------------------------------------------------
// WAT-compatible exports for WIT validation compatibility
// ---------------------------------------------------------------------------

/// Required WIT export: `name` — returns plugin identity string.
///
/// Used by PluginRuntime::load_plugin → discovery::validate_wit_interface.
/// Returns "crowdstrike-oauth2" (must match plugin_id in plugin.toml).
pub fn plugin_name() -> &'static str {
    "crowdstrike-oauth2"
}

/// Required WIT export: `version` — returns plugin semver string.
///
/// Used by PluginRuntime::load_plugin → discovery::validate_wit_interface.
pub fn plugin_version() -> &'static str {
    "0.1.0"
}

// ---------------------------------------------------------------------------
// Unit tests (native target only — these test the pure Rust logic, not WASM ABI)
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    /// auth_type_name() MUST return "oauth2_client_credentials" per INV-AUTH-OPEN-003 Rule A.
    #[test]
    fn test_auth_type_name_returns_canonical_value() {
        assert_eq!(
            auth_type_name(),
            "oauth2_client_credentials",
            "auth_type_name() must return 'oauth2_client_credentials' per INV-AUTH-OPEN-003 Rule A \
             (BC-2.01.016); the value MUST match crowdstrike.sensor.toml auth_type field"
        );
    }

    /// Verify auth_type_name() length matches the canonical string (25 bytes).
    ///
    /// "oauth2_client_credentials" has 25 characters (counted: o-a-u-t-h-2-_-c-l-i-e-n-t-_-c-r-e-d-e-n-t-i-a-l-s).
    /// The adversary pass-1 report cited 24 bytes — that is incorrect.
    #[test]
    fn test_auth_type_name_byte_length_is_25() {
        let name = auth_type_name();
        assert_eq!(
            name.len(),
            25,
            "auth_type_name() must be exactly 25 bytes ('oauth2_client_credentials'); got {} bytes",
            name.len()
        );
    }
}
