// S-1.09: ConfirmationTokenStore — Implementation
//
// Story:  S-1.09 — prism-security: Confirmation Tokens (P1)
// BCs:    BC-2.04.009 — Token Generation (100-cap, crypto random, SHA-256 hash)
//         BC-2.04.010 — Token Consumption via confirm_action
//         BC-2.04.011 — Token Expiry at 300 Seconds (DI-007 security invariant)
//         BC-2.04.012 — Content Hash Verification
// VPs:    VP-007 (expiry boundary), VP-008 (single-use), VP-009 (hash mismatch
//         rejects), VP-010 (101st token → error)
//
// Architecture compliance rules:
//   - Token IDs MUST be cryptographically random — NOT sequential, NOT UUIDs
//     (BC-2.04.009 postcondition 1).
//   - Token store MUST enforce hard cap of 100 active tokens (VP-010).
//   - Expired tokens are swept BEFORE the cap check on each generate() call
//     (BC-2.04.009 postcondition "proactive cleanup").
//   - Token is marked consumed atomically (prevents double-execute on retry).
//   - 300-second TTL is NOT configurable per-client (DI-007 security invariant).
//   - Token store is in-memory only (NOT persisted to disk).

use std::time::{Duration, SystemTime};

use dashmap::DashMap;
use rand::Rng;
use serde::{Deserialize, Serialize};
use serde_json::Value;

use prism_core::error::PrismError;

use crate::content_hash::compute_action_hash;

/// The maximum number of active (non-expired, non-consumed) tokens in the store.
///
/// Hard cap enforced by `generate()` after sweeping expired/consumed tokens.
/// When cap is still reached after cleanup, `E-FLAG-007` is returned (VP-010).
pub const TOKEN_CAP: usize = 100;

/// Token validity window (BC-2.04.011 / DI-007 security invariant).
///
/// Immutable. Not configurable per-client.
pub const TOKEN_TTL: Duration = Duration::from_secs(300);

// ─────────────────────────────────────────────────────────────
// ConfirmationToken
// ─────────────────────────────────────────────────────────────

/// A single-use confirmation token for irreversible write operations.
///
/// Generated by `ConfirmationTokenStore::generate()`.
/// Consumed (invalidated) by `ConfirmationTokenStore::consume()`.
///
/// Field-level invariants:
/// - `token_id`: 256-bit cryptographically random hex string (64 chars).
/// - `expires_at`: `created_at + 300s` — boundary-inclusive expiry (>= means expired, VP-007).
/// - `consumed`: set to `true` before execution to prevent double-execute.
/// - `action_hash`: SHA-256 of `compute_action_hash(client_id, tool_name, action_params)`.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct ConfirmationToken {
    /// Cryptographically random token identifier (256-bit hex, 64 chars).
    pub token_id: String,

    /// The `client_id` (OrgSlug) this action targets.
    /// Used to prevent cross-client token replay (BC-2.04.010 postcondition).
    pub client_id: String,

    /// The name of the originating write tool (e.g., `crowdstrike_contain_host`).
    pub tool_name: String,

    /// The original tool parameters as JSON. Stored so `confirm_action` can
    /// re-dispatch without the caller re-supplying params (BC-2.04.009).
    pub action_params: Value,

    /// Human-readable action description for the agent and error recovery
    /// (BC-2.04.009, BC-2.04.011 structured error).
    pub action_summary: String,

    /// SHA-256 of canonically serialized action params (BC-2.04.012).
    pub action_hash: String,

    /// Token creation instant (wall clock).
    pub created_at: SystemTime,

    /// Expiry instant: `created_at + 300s`.
    ///
    /// Expiry check: `now >= expires_at` means expired (boundary inclusive, VP-007).
    pub expires_at: SystemTime,

    /// Single-use flag. Set to `true` before the action is dispatched
    /// (BC-2.04.010 invariant; VP-008).
    pub consumed: bool,
}

impl ConfirmationToken {
    /// Returns `true` if this token is expired at `now`.
    ///
    /// Expiry is boundary-inclusive: `now >= expires_at` means expired (VP-007).
    /// A token at exactly 300s elapsed is expired (EC-001).
    pub fn is_expired(&self, now: SystemTime) -> bool {
        // now >= expires_at → expired (boundary inclusive per VP-007)
        now >= self.expires_at
    }
}

// ─────────────────────────────────────────────────────────────
// ConfirmationTokenStore
// ─────────────────────────────────────────────────────────────

/// In-memory store for active confirmation tokens.
///
/// Thread-safe via `DashMap`. Enforces 100-token hard cap (VP-010).
/// Performs lazy expired token sweep on each `generate()` call (BC-2.04.009).
///
/// # Memory model
/// - Tokens are NOT persisted to disk. A process restart loses all pending
///   confirmations (EC-04-034 — acceptable per the per-analyst stdio model).
/// - Token store MUST NOT exceed 100 active entries at any point.
/// - Consumed tokens are eagerly removed from the map by `consume()`, so
///   `active_count()` (via `DashMap::len()`) is always accurate without filtering.
pub struct ConfirmationTokenStore {
    /// Active token map: token_id → ConfirmationToken.
    ///
    /// DashMap provides interior mutability with per-shard locking.
    tokens: DashMap<String, ConfirmationToken>,
}

impl ConfirmationTokenStore {
    /// Create a new, empty `ConfirmationTokenStore`.
    pub fn new() -> Self {
        Self {
            tokens: DashMap::new(),
        }
    }

    /// Generate a 256-bit cryptographically random token ID as a lowercase hex string.
    fn generate_token_id() -> String {
        let bytes: [u8; 32] = rand::thread_rng().gen();
        bytes.iter().map(|b| format!("{b:02x}")).collect()
    }

    /// Sweep expired tokens from the store.
    ///
    /// Called proactively before each `generate()` (BC-2.04.009 postcondition).
    /// Also callable explicitly for maintenance.
    ///
    /// Consumed tokens are no longer retained in the map (they are eagerly removed
    /// by `consume()`), so only expired tokens need to be swept here.
    ///
    /// Returns the number of tokens swept.
    pub fn sweep_expired(&self) -> usize {
        let now = SystemTime::now();
        let before = self.tokens.len();

        // Retain only tokens that are NOT expired.
        // Consumed tokens are already absent from the map (eagerly removed by consume()).
        self.tokens.retain(|_, token| !token.is_expired(now));

        let after = self.tokens.len();
        before - after
    }

    /// Generate a confirmation token for an irreversible write operation.
    ///
    /// # Preconditions (BC-2.04.009)
    /// - `client_id` is non-empty.
    /// - `tool_name` is non-empty.
    /// - `action_params` is a valid JSON value.
    ///
    /// # Postconditions (BC-2.04.009)
    /// - Expired/consumed tokens are swept from the store BEFORE the cap check.
    /// - If active token count is still >= `TOKEN_CAP` after sweep, returns
    ///   `PrismError::TokenCapExceeded` (E-FLAG-007; VP-010). No eviction occurs.
    /// - Otherwise, creates a `ConfirmationToken` with:
    ///   - `token_id`: 256-bit cryptographically random hex string (64 chars).
    ///   - `action_hash`: SHA-256 of `compute_action_hash(client_id, tool_name, action_params)`.
    ///   - `expires_at = SystemTime::now() + TOKEN_TTL` (300s).
    ///   - `consumed = false`.
    /// - Returns the new token.
    ///
    /// # Invariant
    /// The action is NOT executed during this step.
    pub fn generate(
        &self,
        client_id: &str,
        tool_name: &str,
        action_params: Value,
        action_summary: &str,
    ) -> Result<ConfirmationToken, PrismError> {
        // Step 1: Sweep expired/consumed tokens (lazy cleanup, BC-2.04.009).
        self.sweep_expired();

        // Step 2: Check cap after sweep (VP-010 — no eviction).
        if self.tokens.len() >= TOKEN_CAP {
            return Err(PrismError::TokenCapExceeded);
        }

        // Step 3: Generate token fields.
        let now = SystemTime::now();
        let token_id = Self::generate_token_id();
        let action_hash = compute_action_hash(client_id, tool_name, &action_params);

        let token = ConfirmationToken {
            token_id: token_id.clone(),
            client_id: client_id.to_string(),
            tool_name: tool_name.to_string(),
            action_params,
            action_summary: action_summary.to_string(),
            action_hash,
            created_at: now,
            expires_at: now + TOKEN_TTL,
            consumed: false,
        };

        // Step 4: Insert and return.
        self.tokens.insert(token_id, token.clone());
        Ok(token)
    }

    /// Consume a confirmation token, validating all invariants.
    ///
    /// This is called by `confirm_action` after the capability gate has already
    /// passed. It validates then eagerly removes the token from the store atomically
    /// BEFORE the caller dispatches the action.
    ///
    /// # Validation order (BC-2.04.010)
    /// 1. Token exists in store — if not, `PrismError::TokenNotFound` (E-FLAG-008).
    /// 2. Token not expired (`now < expires_at`) — if expired, `PrismError::TokenExpired`
    ///    (E-FLAG-003; VP-007).
    /// 3. Token not already consumed — since tokens are eagerly removed on consume,
    ///    a missing token_id at step 1 already covers this path. Step 3 is kept as a
    ///    defensive check for the `consumed` field on a freshly-read entry (always false
    ///    for tokens still in the map).
    /// 4. `client_id` matches token's embedded `client_id` (equality only, no config
    ///    lookup) — if mismatch, `PrismError::ConfirmClientIdMismatch` (E-MCP-004).
    /// 5. Content hash matches — if mismatch, `PrismError::TokenContentHashMismatch`
    ///    (E-FLAG-005; VP-009).
    ///
    /// On success, removes the token from the store (eager cleanup — `active_count()`
    /// decreases immediately) and returns the token with `consumed = true` set for
    /// the caller to dispatch the action.
    ///
    /// # Invariant (VP-008)
    /// After a successful `consume()`, any subsequent `consume()` with the same
    /// `token_id` MUST return `TokenNotFound` (E-FLAG-008). No double-execution
    /// is possible.
    pub fn consume(
        &self,
        token_id: &str,
        client_id: &str,
        action_params: &Value,
    ) -> Result<ConfirmationToken, PrismError> {
        let now = SystemTime::now();

        // Step 1: Token must exist — read a snapshot for validation.
        let entry = self
            .tokens
            .get(token_id)
            .ok_or_else(|| PrismError::TokenNotFound {
                token_id: token_id.to_string(),
            })?;

        // Step 2: Token must not be expired.
        if entry.is_expired(now) {
            return Err(PrismError::TokenExpired {
                action_summary: entry.action_summary.clone(),
                retryable: false,
            });
        }

        // Step 3: Defensive consumed check — tokens in the map are always unconsumed
        // because consume() removes them eagerly, but guard against any future code
        // paths that could re-insert a consumed entry.
        if entry.consumed {
            return Err(PrismError::TokenAlreadyConsumed {
                token_id: token_id.to_string(),
                retryable: false,
            });
        }

        // Step 4: client_id must match (equality only — no config lookup).
        if entry.client_id != client_id {
            return Err(PrismError::ConfirmClientIdMismatch {
                token_id: token_id.to_string(),
                retryable: false,
            });
        }

        // Step 5: Content hash must match (BC-2.04.012; VP-009).
        let expected_hash = compute_action_hash(&entry.client_id, &entry.tool_name, action_params);
        if entry.action_hash != expected_hash {
            return Err(PrismError::TokenContentHashMismatch {
                token_id: token_id.to_string(),
                retryable: false,
            });
        }

        // Release the read reference before removing.
        drop(entry);

        // All checks passed — eagerly remove the token so active_count() decreases
        // immediately and subsequent consume() calls return TokenNotFound (VP-008).
        let (_, mut consumed_token) =
            self.tokens
                .remove(token_id)
                .ok_or_else(|| PrismError::TokenNotFound {
                    token_id: token_id.to_string(),
                })?;

        // Mark consumed = true on the returned token so callers can inspect the field.
        consumed_token.consumed = true;

        Ok(consumed_token)
    }

    /// Return the count of active tokens in the store.
    ///
    /// Used for cap enforcement and test assertions.
    ///
    /// Because `consume()` eagerly removes tokens from the map, all entries in the
    /// store are unconsumed by construction. This means `active_count()` can use
    /// `self.tokens.len()` directly without filtering.
    ///
    /// Note: expired tokens that have not yet been swept (via `sweep_expired()` or
    /// the next `generate()` call) are still counted here. In practice the sweep
    /// runs before each `generate()`, so this is accurate for cap enforcement.
    pub fn active_count(&self) -> usize {
        self.tokens.len()
    }
}

impl Default for ConfirmationTokenStore {
    fn default() -> Self {
        Self::new()
    }
}
